// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: privacy.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PrivacyService_Mask_FullMethodName                         = "/privacy.local.PrivacyService/Mask"
	PrivacyService_MaskRecord_FullMethodName                   = "/privacy.local.PrivacyService/MaskRecord"
	PrivacyService_MaskBatch_FullMethodName                    = "/privacy.local.PrivacyService/MaskBatch"
	PrivacyService_MaskDataFrame_FullMethodName                = "/privacy.local.PrivacyService/MaskDataFrame"
	PrivacyService_Hash_FullMethodName                         = "/privacy.local.PrivacyService/Hash"
	PrivacyService_DPCount_FullMethodName                      = "/privacy.local.PrivacyService/DPCount"
	PrivacyService_DPSum_FullMethodName                        = "/privacy.local.PrivacyService/DPSum"
	PrivacyService_DPMean_FullMethodName                       = "/privacy.local.PrivacyService/DPMean"
	PrivacyService_DPHistogram_FullMethodName                  = "/privacy.local.PrivacyService/DPHistogram"
	PrivacyService_DPNoisyCount_FullMethodName                 = "/privacy.local.PrivacyService/DPNoisyCount"
	PrivacyService_DPNoisySum_FullMethodName                   = "/privacy.local.PrivacyService/DPNoisySum"
	PrivacyService_DPNoisyMean_FullMethodName                  = "/privacy.local.PrivacyService/DPNoisyMean"
	PrivacyService_DPNoisyHistogram_FullMethodName             = "/privacy.local.PrivacyService/DPNoisyHistogram"
	PrivacyService_DPChunkedCount_FullMethodName               = "/privacy.local.PrivacyService/DPChunkedCount"
	PrivacyService_DPChunkedSum_FullMethodName                 = "/privacy.local.PrivacyService/DPChunkedSum"
	PrivacyService_DPChunkedMean_FullMethodName                = "/privacy.local.PrivacyService/DPChunkedMean"
	PrivacyService_DPChunkedHistogram_FullMethodName           = "/privacy.local.PrivacyService/DPChunkedHistogram"
	PrivacyService_KAnonymizeRecord_FullMethodName             = "/privacy.local.PrivacyService/KAnonymizeRecord"
	PrivacyService_KAnonymizeTable_FullMethodName              = "/privacy.local.PrivacyService/KAnonymizeTable"
	PrivacyService_KAnonymizeDataFrame_FullMethodName          = "/privacy.local.PrivacyService/KAnonymizeDataFrame"
	PrivacyService_ObfuscateQuery_FullMethodName               = "/privacy.local.PrivacyService/ObfuscateQuery"
	PrivacyService_ObfuscateQueryBatch_FullMethodName          = "/privacy.local.PrivacyService/ObfuscateQueryBatch"
	PrivacyService_Health_FullMethodName                       = "/privacy.local.PrivacyService/Health"
	PrivacyService_RecommendParams_FullMethodName              = "/privacy.local.PrivacyService/RecommendParams"
	PrivacyService_PerturbBinaryBatch_FullMethodName           = "/privacy.local.PrivacyService/PerturbBinaryBatch"
	PrivacyService_PerturbCategoricalBatch_FullMethodName      = "/privacy.local.PrivacyService/PerturbCategoricalBatch"
	PrivacyService_EstimateBinaryFrequency_FullMethodName      = "/privacy.local.PrivacyService/EstimateBinaryFrequency"
	PrivacyService_EstimateCategoricalHistogram_FullMethodName = "/privacy.local.PrivacyService/EstimateCategoricalHistogram"
	PrivacyService_DPAggregate_FullMethodName                  = "/privacy.local.PrivacyService/DPAggregate"
	PrivacyService_DPVectorSum_FullMethodName                  = "/privacy.local.PrivacyService/DPVectorSum"
	PrivacyService_DPAdaptiveClip_FullMethodName               = "/privacy.local.PrivacyService/DPAdaptiveClip"
	PrivacyService_DPGroupBy_FullMethodName                    = "/privacy.local.PrivacyService/DPGroupBy"
	PrivacyService_DPVectorMean_FullMethodName                 = "/privacy.local.PrivacyService/DPVectorMean"
	PrivacyService_DynClassify_FullMethodName                  = "/privacy.local.PrivacyService/DynClassify"
	PrivacyService_DynEval_FullMethodName                      = "/privacy.local.PrivacyService/DynEval"
	PrivacyService_DynEvalRecord_FullMethodName                = "/privacy.local.PrivacyService/DynEvalRecord"
	PrivacyService_DynStandards_FullMethodName                 = "/privacy.local.PrivacyService/DynStandards"
	PrivacyService_DynDomains_FullMethodName                   = "/privacy.local.PrivacyService/DynDomains"
	PrivacyService_DynOperators_FullMethodName                 = "/privacy.local.PrivacyService/DynOperators"
	PrivacyService_DynValidate_FullMethodName                  = "/privacy.local.PrivacyService/DynValidate"
	PrivacyService_DynGenerateProfile_FullMethodName           = "/privacy.local.PrivacyService/DynGenerateProfile"
)

// PrivacyServiceClient is the client API for PrivacyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PrivacyServiceClient interface {
	Mask(ctx context.Context, in *MaskRequest, opts ...grpc.CallOption) (*MaskResponse, error)
	MaskRecord(ctx context.Context, in *MaskRecordRequest, opts ...grpc.CallOption) (*MaskRecordResponse, error)
	MaskBatch(ctx context.Context, in *MaskBatchRequest, opts ...grpc.CallOption) (*MaskBatchResponse, error)
	MaskDataFrame(ctx context.Context, in *MaskDataFrameRequest, opts ...grpc.CallOption) (*MaskDataFrameResponse, error)
	Hash(ctx context.Context, in *HashRequest, opts ...grpc.CallOption) (*HashResponse, error)
	DPCount(ctx context.Context, in *DPRequest, opts ...grpc.CallOption) (*DPResponse, error)
	DPSum(ctx context.Context, in *DPRequest, opts ...grpc.CallOption) (*DPResponse, error)
	DPMean(ctx context.Context, in *DPRequest, opts ...grpc.CallOption) (*DPResponse, error)
	DPHistogram(ctx context.Context, in *DPHistogramRequest, opts ...grpc.CallOption) (*DPHistogramResponse, error)
	DPNoisyCount(ctx context.Context, in *DPNoisyCountRequest, opts ...grpc.CallOption) (*DPResponse, error)
	DPNoisySum(ctx context.Context, in *DPNoisySumRequest, opts ...grpc.CallOption) (*DPResponse, error)
	DPNoisyMean(ctx context.Context, in *DPNoisyMeanRequest, opts ...grpc.CallOption) (*DPResponse, error)
	DPNoisyHistogram(ctx context.Context, in *DPNoisyHistogramRequest, opts ...grpc.CallOption) (*DPHistogramResponse, error)
	DPChunkedCount(ctx context.Context, in *DPChunkedCountRequest, opts ...grpc.CallOption) (*DPResponse, error)
	DPChunkedSum(ctx context.Context, in *DPChunkedSumRequest, opts ...grpc.CallOption) (*DPResponse, error)
	DPChunkedMean(ctx context.Context, in *DPChunkedMeanRequest, opts ...grpc.CallOption) (*DPResponse, error)
	DPChunkedHistogram(ctx context.Context, in *DPChunkedHistogramRequest, opts ...grpc.CallOption) (*DPHistogramResponse, error)
	KAnonymizeRecord(ctx context.Context, in *KAnonymizeRequest, opts ...grpc.CallOption) (*KAnonymizeResponse, error)
	KAnonymizeTable(ctx context.Context, in *KAnonymizeTableRequest, opts ...grpc.CallOption) (*KAnonymizeTableResponse, error)
	KAnonymizeDataFrame(ctx context.Context, in *KAnonymizeDataFrameRequest, opts ...grpc.CallOption) (*KAnonymizeDataFrameResponse, error)
	ObfuscateQuery(ctx context.Context, in *ObfuscateQueryRequest, opts ...grpc.CallOption) (*ObfuscateQueryResponse, error)
	ObfuscateQueryBatch(ctx context.Context, in *ObfuscateQueryBatchRequest, opts ...grpc.CallOption) (*ObfuscateQueryBatchResponse, error)
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	RecommendParams(ctx context.Context, in *RecommendRequest, opts ...grpc.CallOption) (*RecommendResponse, error)
	PerturbBinaryBatch(ctx context.Context, in *PerturbBinaryBatchRequest, opts ...grpc.CallOption) (*PerturbBinaryBatchResponse, error)
	PerturbCategoricalBatch(ctx context.Context, in *PerturbCategoricalBatchRequest, opts ...grpc.CallOption) (*PerturbCategoricalBatchResponse, error)
	EstimateBinaryFrequency(ctx context.Context, in *EstimateBinaryFrequencyRequest, opts ...grpc.CallOption) (*EstimateBinaryFrequencyResponse, error)
	EstimateCategoricalHistogram(ctx context.Context, in *EstimateCategoricalHistogramRequest, opts ...grpc.CallOption) (*EstimateCategoricalHistogramResponse, error)
	DPAggregate(ctx context.Context, in *DPAggregateRequest, opts ...grpc.CallOption) (*DPAggregateResponse, error)
	DPVectorSum(ctx context.Context, in *DPVectorSumRequest, opts ...grpc.CallOption) (*DPVectorSumResponse, error)
	DPAdaptiveClip(ctx context.Context, in *DPAdaptiveClipRequest, opts ...grpc.CallOption) (*DPAdaptiveClipResponse, error)
	DPGroupBy(ctx context.Context, in *DPGroupByRequest, opts ...grpc.CallOption) (*DPGroupByResponse, error)
	DPVectorMean(ctx context.Context, in *DPVectorMeanRequest, opts ...grpc.CallOption) (*DPVectorMeanResponse, error)
	DynClassify(ctx context.Context, in *DynClassificationRequest, opts ...grpc.CallOption) (*DynClassificationResponse, error)
	DynEval(ctx context.Context, in *DynEvalRequest, opts ...grpc.CallOption) (*DynEvalResponse, error)
	DynEvalRecord(ctx context.Context, in *DynEvalRecordRequest, opts ...grpc.CallOption) (*DynEvalRecordResponse, error)
	DynStandards(ctx context.Context, in *DynStandardsRequest, opts ...grpc.CallOption) (*DynStandardsResponse, error)
	DynDomains(ctx context.Context, in *DynDomainsRequest, opts ...grpc.CallOption) (*DynDomainsResponse, error)
	DynOperators(ctx context.Context, in *DynOperatorsRequest, opts ...grpc.CallOption) (*DynOperatorsResponse, error)
	DynValidate(ctx context.Context, in *DynValidateRequest, opts ...grpc.CallOption) (*DynValidateResponse, error)
	DynGenerateProfile(ctx context.Context, in *DynGenerateProfileRequest, opts ...grpc.CallOption) (*DynGenerateProfileResponse, error)
}

type privacyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPrivacyServiceClient(cc grpc.ClientConnInterface) PrivacyServiceClient {
	return &privacyServiceClient{cc}
}

func (c *privacyServiceClient) Mask(ctx context.Context, in *MaskRequest, opts ...grpc.CallOption) (*MaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MaskResponse)
	err := c.cc.Invoke(ctx, PrivacyService_Mask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privacyServiceClient) MaskRecord(ctx context.Context, in *MaskRecordRequest, opts ...grpc.CallOption) (*MaskRecordResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MaskRecordResponse)
	err := c.cc.Invoke(ctx, PrivacyService_MaskRecord_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privacyServiceClient) MaskBatch(ctx context.Context, in *MaskBatchRequest, opts ...grpc.CallOption) (*MaskBatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MaskBatchResponse)
	err := c.cc.Invoke(ctx, PrivacyService_MaskBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privacyServiceClient) MaskDataFrame(ctx context.Context, in *MaskDataFrameRequest, opts ...grpc.CallOption) (*MaskDataFrameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MaskDataFrameResponse)
	err := c.cc.Invoke(ctx, PrivacyService_MaskDataFrame_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privacyServiceClient) Hash(ctx context.Context, in *HashRequest, opts ...grpc.CallOption) (*HashResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HashResponse)
	err := c.cc.Invoke(ctx, PrivacyService_Hash_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privacyServiceClient) DPCount(ctx context.Context, in *DPRequest, opts ...grpc.CallOption) (*DPResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DPResponse)
	err := c.cc.Invoke(ctx, PrivacyService_DPCount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privacyServiceClient) DPSum(ctx context.Context, in *DPRequest, opts ...grpc.CallOption) (*DPResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DPResponse)
	err := c.cc.Invoke(ctx, PrivacyService_DPSum_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privacyServiceClient) DPMean(ctx context.Context, in *DPRequest, opts ...grpc.CallOption) (*DPResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DPResponse)
	err := c.cc.Invoke(ctx, PrivacyService_DPMean_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privacyServiceClient) DPHistogram(ctx context.Context, in *DPHistogramRequest, opts ...grpc.CallOption) (*DPHistogramResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DPHistogramResponse)
	err := c.cc.Invoke(ctx, PrivacyService_DPHistogram_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privacyServiceClient) DPNoisyCount(ctx context.Context, in *DPNoisyCountRequest, opts ...grpc.CallOption) (*DPResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DPResponse)
	err := c.cc.Invoke(ctx, PrivacyService_DPNoisyCount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privacyServiceClient) DPNoisySum(ctx context.Context, in *DPNoisySumRequest, opts ...grpc.CallOption) (*DPResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DPResponse)
	err := c.cc.Invoke(ctx, PrivacyService_DPNoisySum_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privacyServiceClient) DPNoisyMean(ctx context.Context, in *DPNoisyMeanRequest, opts ...grpc.CallOption) (*DPResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DPResponse)
	err := c.cc.Invoke(ctx, PrivacyService_DPNoisyMean_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privacyServiceClient) DPNoisyHistogram(ctx context.Context, in *DPNoisyHistogramRequest, opts ...grpc.CallOption) (*DPHistogramResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DPHistogramResponse)
	err := c.cc.Invoke(ctx, PrivacyService_DPNoisyHistogram_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privacyServiceClient) DPChunkedCount(ctx context.Context, in *DPChunkedCountRequest, opts ...grpc.CallOption) (*DPResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DPResponse)
	err := c.cc.Invoke(ctx, PrivacyService_DPChunkedCount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privacyServiceClient) DPChunkedSum(ctx context.Context, in *DPChunkedSumRequest, opts ...grpc.CallOption) (*DPResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DPResponse)
	err := c.cc.Invoke(ctx, PrivacyService_DPChunkedSum_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privacyServiceClient) DPChunkedMean(ctx context.Context, in *DPChunkedMeanRequest, opts ...grpc.CallOption) (*DPResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DPResponse)
	err := c.cc.Invoke(ctx, PrivacyService_DPChunkedMean_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privacyServiceClient) DPChunkedHistogram(ctx context.Context, in *DPChunkedHistogramRequest, opts ...grpc.CallOption) (*DPHistogramResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DPHistogramResponse)
	err := c.cc.Invoke(ctx, PrivacyService_DPChunkedHistogram_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privacyServiceClient) KAnonymizeRecord(ctx context.Context, in *KAnonymizeRequest, opts ...grpc.CallOption) (*KAnonymizeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KAnonymizeResponse)
	err := c.cc.Invoke(ctx, PrivacyService_KAnonymizeRecord_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privacyServiceClient) KAnonymizeTable(ctx context.Context, in *KAnonymizeTableRequest, opts ...grpc.CallOption) (*KAnonymizeTableResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KAnonymizeTableResponse)
	err := c.cc.Invoke(ctx, PrivacyService_KAnonymizeTable_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privacyServiceClient) KAnonymizeDataFrame(ctx context.Context, in *KAnonymizeDataFrameRequest, opts ...grpc.CallOption) (*KAnonymizeDataFrameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KAnonymizeDataFrameResponse)
	err := c.cc.Invoke(ctx, PrivacyService_KAnonymizeDataFrame_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privacyServiceClient) ObfuscateQuery(ctx context.Context, in *ObfuscateQueryRequest, opts ...grpc.CallOption) (*ObfuscateQueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ObfuscateQueryResponse)
	err := c.cc.Invoke(ctx, PrivacyService_ObfuscateQuery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privacyServiceClient) ObfuscateQueryBatch(ctx context.Context, in *ObfuscateQueryBatchRequest, opts ...grpc.CallOption) (*ObfuscateQueryBatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ObfuscateQueryBatchResponse)
	err := c.cc.Invoke(ctx, PrivacyService_ObfuscateQueryBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privacyServiceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, PrivacyService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privacyServiceClient) RecommendParams(ctx context.Context, in *RecommendRequest, opts ...grpc.CallOption) (*RecommendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecommendResponse)
	err := c.cc.Invoke(ctx, PrivacyService_RecommendParams_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privacyServiceClient) PerturbBinaryBatch(ctx context.Context, in *PerturbBinaryBatchRequest, opts ...grpc.CallOption) (*PerturbBinaryBatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PerturbBinaryBatchResponse)
	err := c.cc.Invoke(ctx, PrivacyService_PerturbBinaryBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privacyServiceClient) PerturbCategoricalBatch(ctx context.Context, in *PerturbCategoricalBatchRequest, opts ...grpc.CallOption) (*PerturbCategoricalBatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PerturbCategoricalBatchResponse)
	err := c.cc.Invoke(ctx, PrivacyService_PerturbCategoricalBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privacyServiceClient) EstimateBinaryFrequency(ctx context.Context, in *EstimateBinaryFrequencyRequest, opts ...grpc.CallOption) (*EstimateBinaryFrequencyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EstimateBinaryFrequencyResponse)
	err := c.cc.Invoke(ctx, PrivacyService_EstimateBinaryFrequency_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privacyServiceClient) EstimateCategoricalHistogram(ctx context.Context, in *EstimateCategoricalHistogramRequest, opts ...grpc.CallOption) (*EstimateCategoricalHistogramResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EstimateCategoricalHistogramResponse)
	err := c.cc.Invoke(ctx, PrivacyService_EstimateCategoricalHistogram_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privacyServiceClient) DPAggregate(ctx context.Context, in *DPAggregateRequest, opts ...grpc.CallOption) (*DPAggregateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DPAggregateResponse)
	err := c.cc.Invoke(ctx, PrivacyService_DPAggregate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privacyServiceClient) DPVectorSum(ctx context.Context, in *DPVectorSumRequest, opts ...grpc.CallOption) (*DPVectorSumResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DPVectorSumResponse)
	err := c.cc.Invoke(ctx, PrivacyService_DPVectorSum_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privacyServiceClient) DPAdaptiveClip(ctx context.Context, in *DPAdaptiveClipRequest, opts ...grpc.CallOption) (*DPAdaptiveClipResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DPAdaptiveClipResponse)
	err := c.cc.Invoke(ctx, PrivacyService_DPAdaptiveClip_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privacyServiceClient) DPGroupBy(ctx context.Context, in *DPGroupByRequest, opts ...grpc.CallOption) (*DPGroupByResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DPGroupByResponse)
	err := c.cc.Invoke(ctx, PrivacyService_DPGroupBy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privacyServiceClient) DPVectorMean(ctx context.Context, in *DPVectorMeanRequest, opts ...grpc.CallOption) (*DPVectorMeanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DPVectorMeanResponse)
	err := c.cc.Invoke(ctx, PrivacyService_DPVectorMean_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privacyServiceClient) DynClassify(ctx context.Context, in *DynClassificationRequest, opts ...grpc.CallOption) (*DynClassificationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DynClassificationResponse)
	err := c.cc.Invoke(ctx, PrivacyService_DynClassify_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privacyServiceClient) DynEval(ctx context.Context, in *DynEvalRequest, opts ...grpc.CallOption) (*DynEvalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DynEvalResponse)
	err := c.cc.Invoke(ctx, PrivacyService_DynEval_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privacyServiceClient) DynEvalRecord(ctx context.Context, in *DynEvalRecordRequest, opts ...grpc.CallOption) (*DynEvalRecordResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DynEvalRecordResponse)
	err := c.cc.Invoke(ctx, PrivacyService_DynEvalRecord_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privacyServiceClient) DynStandards(ctx context.Context, in *DynStandardsRequest, opts ...grpc.CallOption) (*DynStandardsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DynStandardsResponse)
	err := c.cc.Invoke(ctx, PrivacyService_DynStandards_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privacyServiceClient) DynDomains(ctx context.Context, in *DynDomainsRequest, opts ...grpc.CallOption) (*DynDomainsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DynDomainsResponse)
	err := c.cc.Invoke(ctx, PrivacyService_DynDomains_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privacyServiceClient) DynOperators(ctx context.Context, in *DynOperatorsRequest, opts ...grpc.CallOption) (*DynOperatorsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DynOperatorsResponse)
	err := c.cc.Invoke(ctx, PrivacyService_DynOperators_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privacyServiceClient) DynValidate(ctx context.Context, in *DynValidateRequest, opts ...grpc.CallOption) (*DynValidateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DynValidateResponse)
	err := c.cc.Invoke(ctx, PrivacyService_DynValidate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privacyServiceClient) DynGenerateProfile(ctx context.Context, in *DynGenerateProfileRequest, opts ...grpc.CallOption) (*DynGenerateProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DynGenerateProfileResponse)
	err := c.cc.Invoke(ctx, PrivacyService_DynGenerateProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PrivacyServiceServer is the server API for PrivacyService service.
// All implementations must embed UnimplementedPrivacyServiceServer
// for forward compatibility.
type PrivacyServiceServer interface {
	Mask(context.Context, *MaskRequest) (*MaskResponse, error)
	MaskRecord(context.Context, *MaskRecordRequest) (*MaskRecordResponse, error)
	MaskBatch(context.Context, *MaskBatchRequest) (*MaskBatchResponse, error)
	MaskDataFrame(context.Context, *MaskDataFrameRequest) (*MaskDataFrameResponse, error)
	Hash(context.Context, *HashRequest) (*HashResponse, error)
	DPCount(context.Context, *DPRequest) (*DPResponse, error)
	DPSum(context.Context, *DPRequest) (*DPResponse, error)
	DPMean(context.Context, *DPRequest) (*DPResponse, error)
	DPHistogram(context.Context, *DPHistogramRequest) (*DPHistogramResponse, error)
	DPNoisyCount(context.Context, *DPNoisyCountRequest) (*DPResponse, error)
	DPNoisySum(context.Context, *DPNoisySumRequest) (*DPResponse, error)
	DPNoisyMean(context.Context, *DPNoisyMeanRequest) (*DPResponse, error)
	DPNoisyHistogram(context.Context, *DPNoisyHistogramRequest) (*DPHistogramResponse, error)
	DPChunkedCount(context.Context, *DPChunkedCountRequest) (*DPResponse, error)
	DPChunkedSum(context.Context, *DPChunkedSumRequest) (*DPResponse, error)
	DPChunkedMean(context.Context, *DPChunkedMeanRequest) (*DPResponse, error)
	DPChunkedHistogram(context.Context, *DPChunkedHistogramRequest) (*DPHistogramResponse, error)
	KAnonymizeRecord(context.Context, *KAnonymizeRequest) (*KAnonymizeResponse, error)
	KAnonymizeTable(context.Context, *KAnonymizeTableRequest) (*KAnonymizeTableResponse, error)
	KAnonymizeDataFrame(context.Context, *KAnonymizeDataFrameRequest) (*KAnonymizeDataFrameResponse, error)
	ObfuscateQuery(context.Context, *ObfuscateQueryRequest) (*ObfuscateQueryResponse, error)
	ObfuscateQueryBatch(context.Context, *ObfuscateQueryBatchRequest) (*ObfuscateQueryBatchResponse, error)
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	RecommendParams(context.Context, *RecommendRequest) (*RecommendResponse, error)
	PerturbBinaryBatch(context.Context, *PerturbBinaryBatchRequest) (*PerturbBinaryBatchResponse, error)
	PerturbCategoricalBatch(context.Context, *PerturbCategoricalBatchRequest) (*PerturbCategoricalBatchResponse, error)
	EstimateBinaryFrequency(context.Context, *EstimateBinaryFrequencyRequest) (*EstimateBinaryFrequencyResponse, error)
	EstimateCategoricalHistogram(context.Context, *EstimateCategoricalHistogramRequest) (*EstimateCategoricalHistogramResponse, error)
	DPAggregate(context.Context, *DPAggregateRequest) (*DPAggregateResponse, error)
	DPVectorSum(context.Context, *DPVectorSumRequest) (*DPVectorSumResponse, error)
	DPAdaptiveClip(context.Context, *DPAdaptiveClipRequest) (*DPAdaptiveClipResponse, error)
	DPGroupBy(context.Context, *DPGroupByRequest) (*DPGroupByResponse, error)
	DPVectorMean(context.Context, *DPVectorMeanRequest) (*DPVectorMeanResponse, error)
	DynClassify(context.Context, *DynClassificationRequest) (*DynClassificationResponse, error)
	DynEval(context.Context, *DynEvalRequest) (*DynEvalResponse, error)
	DynEvalRecord(context.Context, *DynEvalRecordRequest) (*DynEvalRecordResponse, error)
	DynStandards(context.Context, *DynStandardsRequest) (*DynStandardsResponse, error)
	DynDomains(context.Context, *DynDomainsRequest) (*DynDomainsResponse, error)
	DynOperators(context.Context, *DynOperatorsRequest) (*DynOperatorsResponse, error)
	DynValidate(context.Context, *DynValidateRequest) (*DynValidateResponse, error)
	DynGenerateProfile(context.Context, *DynGenerateProfileRequest) (*DynGenerateProfileResponse, error)
	mustEmbedUnimplementedPrivacyServiceServer()
}

// UnimplementedPrivacyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPrivacyServiceServer struct{}

func (UnimplementedPrivacyServiceServer) Mask(context.Context, *MaskRequest) (*MaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Mask not implemented")
}
func (UnimplementedPrivacyServiceServer) MaskRecord(context.Context, *MaskRecordRequest) (*MaskRecordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MaskRecord not implemented")
}
func (UnimplementedPrivacyServiceServer) MaskBatch(context.Context, *MaskBatchRequest) (*MaskBatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MaskBatch not implemented")
}
func (UnimplementedPrivacyServiceServer) MaskDataFrame(context.Context, *MaskDataFrameRequest) (*MaskDataFrameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MaskDataFrame not implemented")
}
func (UnimplementedPrivacyServiceServer) Hash(context.Context, *HashRequest) (*HashResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Hash not implemented")
}
func (UnimplementedPrivacyServiceServer) DPCount(context.Context, *DPRequest) (*DPResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DPCount not implemented")
}
func (UnimplementedPrivacyServiceServer) DPSum(context.Context, *DPRequest) (*DPResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DPSum not implemented")
}
func (UnimplementedPrivacyServiceServer) DPMean(context.Context, *DPRequest) (*DPResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DPMean not implemented")
}
func (UnimplementedPrivacyServiceServer) DPHistogram(context.Context, *DPHistogramRequest) (*DPHistogramResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DPHistogram not implemented")
}
func (UnimplementedPrivacyServiceServer) DPNoisyCount(context.Context, *DPNoisyCountRequest) (*DPResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DPNoisyCount not implemented")
}
func (UnimplementedPrivacyServiceServer) DPNoisySum(context.Context, *DPNoisySumRequest) (*DPResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DPNoisySum not implemented")
}
func (UnimplementedPrivacyServiceServer) DPNoisyMean(context.Context, *DPNoisyMeanRequest) (*DPResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DPNoisyMean not implemented")
}
func (UnimplementedPrivacyServiceServer) DPNoisyHistogram(context.Context, *DPNoisyHistogramRequest) (*DPHistogramResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DPNoisyHistogram not implemented")
}
func (UnimplementedPrivacyServiceServer) DPChunkedCount(context.Context, *DPChunkedCountRequest) (*DPResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DPChunkedCount not implemented")
}
func (UnimplementedPrivacyServiceServer) DPChunkedSum(context.Context, *DPChunkedSumRequest) (*DPResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DPChunkedSum not implemented")
}
func (UnimplementedPrivacyServiceServer) DPChunkedMean(context.Context, *DPChunkedMeanRequest) (*DPResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DPChunkedMean not implemented")
}
func (UnimplementedPrivacyServiceServer) DPChunkedHistogram(context.Context, *DPChunkedHistogramRequest) (*DPHistogramResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DPChunkedHistogram not implemented")
}
func (UnimplementedPrivacyServiceServer) KAnonymizeRecord(context.Context, *KAnonymizeRequest) (*KAnonymizeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KAnonymizeRecord not implemented")
}
func (UnimplementedPrivacyServiceServer) KAnonymizeTable(context.Context, *KAnonymizeTableRequest) (*KAnonymizeTableResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KAnonymizeTable not implemented")
}
func (UnimplementedPrivacyServiceServer) KAnonymizeDataFrame(context.Context, *KAnonymizeDataFrameRequest) (*KAnonymizeDataFrameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KAnonymizeDataFrame not implemented")
}
func (UnimplementedPrivacyServiceServer) ObfuscateQuery(context.Context, *ObfuscateQueryRequest) (*ObfuscateQueryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ObfuscateQuery not implemented")
}
func (UnimplementedPrivacyServiceServer) ObfuscateQueryBatch(context.Context, *ObfuscateQueryBatchRequest) (*ObfuscateQueryBatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ObfuscateQueryBatch not implemented")
}
func (UnimplementedPrivacyServiceServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedPrivacyServiceServer) RecommendParams(context.Context, *RecommendRequest) (*RecommendResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecommendParams not implemented")
}
func (UnimplementedPrivacyServiceServer) PerturbBinaryBatch(context.Context, *PerturbBinaryBatchRequest) (*PerturbBinaryBatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PerturbBinaryBatch not implemented")
}
func (UnimplementedPrivacyServiceServer) PerturbCategoricalBatch(context.Context, *PerturbCategoricalBatchRequest) (*PerturbCategoricalBatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PerturbCategoricalBatch not implemented")
}
func (UnimplementedPrivacyServiceServer) EstimateBinaryFrequency(context.Context, *EstimateBinaryFrequencyRequest) (*EstimateBinaryFrequencyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EstimateBinaryFrequency not implemented")
}
func (UnimplementedPrivacyServiceServer) EstimateCategoricalHistogram(context.Context, *EstimateCategoricalHistogramRequest) (*EstimateCategoricalHistogramResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EstimateCategoricalHistogram not implemented")
}
func (UnimplementedPrivacyServiceServer) DPAggregate(context.Context, *DPAggregateRequest) (*DPAggregateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DPAggregate not implemented")
}
func (UnimplementedPrivacyServiceServer) DPVectorSum(context.Context, *DPVectorSumRequest) (*DPVectorSumResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DPVectorSum not implemented")
}
func (UnimplementedPrivacyServiceServer) DPAdaptiveClip(context.Context, *DPAdaptiveClipRequest) (*DPAdaptiveClipResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DPAdaptiveClip not implemented")
}
func (UnimplementedPrivacyServiceServer) DPGroupBy(context.Context, *DPGroupByRequest) (*DPGroupByResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DPGroupBy not implemented")
}
func (UnimplementedPrivacyServiceServer) DPVectorMean(context.Context, *DPVectorMeanRequest) (*DPVectorMeanResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DPVectorMean not implemented")
}
func (UnimplementedPrivacyServiceServer) DynClassify(context.Context, *DynClassificationRequest) (*DynClassificationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DynClassify not implemented")
}
func (UnimplementedPrivacyServiceServer) DynEval(context.Context, *DynEvalRequest) (*DynEvalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DynEval not implemented")
}
func (UnimplementedPrivacyServiceServer) DynEvalRecord(context.Context, *DynEvalRecordRequest) (*DynEvalRecordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DynEvalRecord not implemented")
}
func (UnimplementedPrivacyServiceServer) DynStandards(context.Context, *DynStandardsRequest) (*DynStandardsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DynStandards not implemented")
}
func (UnimplementedPrivacyServiceServer) DynDomains(context.Context, *DynDomainsRequest) (*DynDomainsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DynDomains not implemented")
}
func (UnimplementedPrivacyServiceServer) DynOperators(context.Context, *DynOperatorsRequest) (*DynOperatorsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DynOperators not implemented")
}
func (UnimplementedPrivacyServiceServer) DynValidate(context.Context, *DynValidateRequest) (*DynValidateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DynValidate not implemented")
}
func (UnimplementedPrivacyServiceServer) DynGenerateProfile(context.Context, *DynGenerateProfileRequest) (*DynGenerateProfileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DynGenerateProfile not implemented")
}
func (UnimplementedPrivacyServiceServer) mustEmbedUnimplementedPrivacyServiceServer() {}
func (UnimplementedPrivacyServiceServer) testEmbeddedByValue()                        {}

// UnsafePrivacyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PrivacyServiceServer will
// result in compilation errors.
type UnsafePrivacyServiceServer interface {
	mustEmbedUnimplementedPrivacyServiceServer()
}

func RegisterPrivacyServiceServer(s grpc.ServiceRegistrar, srv PrivacyServiceServer) {
	// If the following call pancis, it indicates UnimplementedPrivacyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PrivacyService_ServiceDesc, srv)
}

func _PrivacyService_Mask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivacyServiceServer).Mask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivacyService_Mask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivacyServiceServer).Mask(ctx, req.(*MaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivacyService_MaskRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MaskRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivacyServiceServer).MaskRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivacyService_MaskRecord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivacyServiceServer).MaskRecord(ctx, req.(*MaskRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivacyService_MaskBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MaskBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivacyServiceServer).MaskBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivacyService_MaskBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivacyServiceServer).MaskBatch(ctx, req.(*MaskBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivacyService_MaskDataFrame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MaskDataFrameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivacyServiceServer).MaskDataFrame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivacyService_MaskDataFrame_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivacyServiceServer).MaskDataFrame(ctx, req.(*MaskDataFrameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivacyService_Hash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HashRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivacyServiceServer).Hash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivacyService_Hash_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivacyServiceServer).Hash(ctx, req.(*HashRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivacyService_DPCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivacyServiceServer).DPCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivacyService_DPCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivacyServiceServer).DPCount(ctx, req.(*DPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivacyService_DPSum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivacyServiceServer).DPSum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivacyService_DPSum_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivacyServiceServer).DPSum(ctx, req.(*DPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivacyService_DPMean_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivacyServiceServer).DPMean(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivacyService_DPMean_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivacyServiceServer).DPMean(ctx, req.(*DPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivacyService_DPHistogram_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DPHistogramRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivacyServiceServer).DPHistogram(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivacyService_DPHistogram_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivacyServiceServer).DPHistogram(ctx, req.(*DPHistogramRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivacyService_DPNoisyCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DPNoisyCountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivacyServiceServer).DPNoisyCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivacyService_DPNoisyCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivacyServiceServer).DPNoisyCount(ctx, req.(*DPNoisyCountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivacyService_DPNoisySum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DPNoisySumRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivacyServiceServer).DPNoisySum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivacyService_DPNoisySum_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivacyServiceServer).DPNoisySum(ctx, req.(*DPNoisySumRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivacyService_DPNoisyMean_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DPNoisyMeanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivacyServiceServer).DPNoisyMean(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivacyService_DPNoisyMean_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivacyServiceServer).DPNoisyMean(ctx, req.(*DPNoisyMeanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivacyService_DPNoisyHistogram_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DPNoisyHistogramRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivacyServiceServer).DPNoisyHistogram(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivacyService_DPNoisyHistogram_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivacyServiceServer).DPNoisyHistogram(ctx, req.(*DPNoisyHistogramRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivacyService_DPChunkedCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DPChunkedCountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivacyServiceServer).DPChunkedCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivacyService_DPChunkedCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivacyServiceServer).DPChunkedCount(ctx, req.(*DPChunkedCountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivacyService_DPChunkedSum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DPChunkedSumRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivacyServiceServer).DPChunkedSum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivacyService_DPChunkedSum_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivacyServiceServer).DPChunkedSum(ctx, req.(*DPChunkedSumRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivacyService_DPChunkedMean_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DPChunkedMeanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivacyServiceServer).DPChunkedMean(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivacyService_DPChunkedMean_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivacyServiceServer).DPChunkedMean(ctx, req.(*DPChunkedMeanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivacyService_DPChunkedHistogram_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DPChunkedHistogramRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivacyServiceServer).DPChunkedHistogram(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivacyService_DPChunkedHistogram_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivacyServiceServer).DPChunkedHistogram(ctx, req.(*DPChunkedHistogramRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivacyService_KAnonymizeRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KAnonymizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivacyServiceServer).KAnonymizeRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivacyService_KAnonymizeRecord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivacyServiceServer).KAnonymizeRecord(ctx, req.(*KAnonymizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivacyService_KAnonymizeTable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KAnonymizeTableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivacyServiceServer).KAnonymizeTable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivacyService_KAnonymizeTable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivacyServiceServer).KAnonymizeTable(ctx, req.(*KAnonymizeTableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivacyService_KAnonymizeDataFrame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KAnonymizeDataFrameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivacyServiceServer).KAnonymizeDataFrame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivacyService_KAnonymizeDataFrame_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivacyServiceServer).KAnonymizeDataFrame(ctx, req.(*KAnonymizeDataFrameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivacyService_ObfuscateQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ObfuscateQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivacyServiceServer).ObfuscateQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivacyService_ObfuscateQuery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivacyServiceServer).ObfuscateQuery(ctx, req.(*ObfuscateQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivacyService_ObfuscateQueryBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ObfuscateQueryBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivacyServiceServer).ObfuscateQueryBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivacyService_ObfuscateQueryBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivacyServiceServer).ObfuscateQueryBatch(ctx, req.(*ObfuscateQueryBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivacyService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivacyServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivacyService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivacyServiceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivacyService_RecommendParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecommendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivacyServiceServer).RecommendParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivacyService_RecommendParams_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivacyServiceServer).RecommendParams(ctx, req.(*RecommendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivacyService_PerturbBinaryBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PerturbBinaryBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivacyServiceServer).PerturbBinaryBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivacyService_PerturbBinaryBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivacyServiceServer).PerturbBinaryBatch(ctx, req.(*PerturbBinaryBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivacyService_PerturbCategoricalBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PerturbCategoricalBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivacyServiceServer).PerturbCategoricalBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivacyService_PerturbCategoricalBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivacyServiceServer).PerturbCategoricalBatch(ctx, req.(*PerturbCategoricalBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivacyService_EstimateBinaryFrequency_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EstimateBinaryFrequencyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivacyServiceServer).EstimateBinaryFrequency(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivacyService_EstimateBinaryFrequency_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivacyServiceServer).EstimateBinaryFrequency(ctx, req.(*EstimateBinaryFrequencyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivacyService_EstimateCategoricalHistogram_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EstimateCategoricalHistogramRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivacyServiceServer).EstimateCategoricalHistogram(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivacyService_EstimateCategoricalHistogram_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivacyServiceServer).EstimateCategoricalHistogram(ctx, req.(*EstimateCategoricalHistogramRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivacyService_DPAggregate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DPAggregateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivacyServiceServer).DPAggregate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivacyService_DPAggregate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivacyServiceServer).DPAggregate(ctx, req.(*DPAggregateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivacyService_DPVectorSum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DPVectorSumRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivacyServiceServer).DPVectorSum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivacyService_DPVectorSum_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivacyServiceServer).DPVectorSum(ctx, req.(*DPVectorSumRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivacyService_DPAdaptiveClip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DPAdaptiveClipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivacyServiceServer).DPAdaptiveClip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivacyService_DPAdaptiveClip_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivacyServiceServer).DPAdaptiveClip(ctx, req.(*DPAdaptiveClipRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivacyService_DPGroupBy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DPGroupByRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivacyServiceServer).DPGroupBy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivacyService_DPGroupBy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivacyServiceServer).DPGroupBy(ctx, req.(*DPGroupByRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivacyService_DPVectorMean_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DPVectorMeanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivacyServiceServer).DPVectorMean(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivacyService_DPVectorMean_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivacyServiceServer).DPVectorMean(ctx, req.(*DPVectorMeanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivacyService_DynClassify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DynClassificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivacyServiceServer).DynClassify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivacyService_DynClassify_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivacyServiceServer).DynClassify(ctx, req.(*DynClassificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivacyService_DynEval_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DynEvalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivacyServiceServer).DynEval(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivacyService_DynEval_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivacyServiceServer).DynEval(ctx, req.(*DynEvalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivacyService_DynEvalRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DynEvalRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivacyServiceServer).DynEvalRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivacyService_DynEvalRecord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivacyServiceServer).DynEvalRecord(ctx, req.(*DynEvalRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivacyService_DynStandards_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DynStandardsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivacyServiceServer).DynStandards(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivacyService_DynStandards_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivacyServiceServer).DynStandards(ctx, req.(*DynStandardsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivacyService_DynDomains_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DynDomainsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivacyServiceServer).DynDomains(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivacyService_DynDomains_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivacyServiceServer).DynDomains(ctx, req.(*DynDomainsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivacyService_DynOperators_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DynOperatorsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivacyServiceServer).DynOperators(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivacyService_DynOperators_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivacyServiceServer).DynOperators(ctx, req.(*DynOperatorsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivacyService_DynValidate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DynValidateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivacyServiceServer).DynValidate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivacyService_DynValidate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivacyServiceServer).DynValidate(ctx, req.(*DynValidateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivacyService_DynGenerateProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DynGenerateProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivacyServiceServer).DynGenerateProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivacyService_DynGenerateProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivacyServiceServer).DynGenerateProfile(ctx, req.(*DynGenerateProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PrivacyService_ServiceDesc is the grpc.ServiceDesc for PrivacyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PrivacyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "privacy.local.PrivacyService",
	HandlerType: (*PrivacyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Mask",
			Handler:    _PrivacyService_Mask_Handler,
		},
		{
			MethodName: "MaskRecord",
			Handler:    _PrivacyService_MaskRecord_Handler,
		},
		{
			MethodName: "MaskBatch",
			Handler:    _PrivacyService_MaskBatch_Handler,
		},
		{
			MethodName: "MaskDataFrame",
			Handler:    _PrivacyService_MaskDataFrame_Handler,
		},
		{
			MethodName: "Hash",
			Handler:    _PrivacyService_Hash_Handler,
		},
		{
			MethodName: "DPCount",
			Handler:    _PrivacyService_DPCount_Handler,
		},
		{
			MethodName: "DPSum",
			Handler:    _PrivacyService_DPSum_Handler,
		},
		{
			MethodName: "DPMean",
			Handler:    _PrivacyService_DPMean_Handler,
		},
		{
			MethodName: "DPHistogram",
			Handler:    _PrivacyService_DPHistogram_Handler,
		},
		{
			MethodName: "DPNoisyCount",
			Handler:    _PrivacyService_DPNoisyCount_Handler,
		},
		{
			MethodName: "DPNoisySum",
			Handler:    _PrivacyService_DPNoisySum_Handler,
		},
		{
			MethodName: "DPNoisyMean",
			Handler:    _PrivacyService_DPNoisyMean_Handler,
		},
		{
			MethodName: "DPNoisyHistogram",
			Handler:    _PrivacyService_DPNoisyHistogram_Handler,
		},
		{
			MethodName: "DPChunkedCount",
			Handler:    _PrivacyService_DPChunkedCount_Handler,
		},
		{
			MethodName: "DPChunkedSum",
			Handler:    _PrivacyService_DPChunkedSum_Handler,
		},
		{
			MethodName: "DPChunkedMean",
			Handler:    _PrivacyService_DPChunkedMean_Handler,
		},
		{
			MethodName: "DPChunkedHistogram",
			Handler:    _PrivacyService_DPChunkedHistogram_Handler,
		},
		{
			MethodName: "KAnonymizeRecord",
			Handler:    _PrivacyService_KAnonymizeRecord_Handler,
		},
		{
			MethodName: "KAnonymizeTable",
			Handler:    _PrivacyService_KAnonymizeTable_Handler,
		},
		{
			MethodName: "KAnonymizeDataFrame",
			Handler:    _PrivacyService_KAnonymizeDataFrame_Handler,
		},
		{
			MethodName: "ObfuscateQuery",
			Handler:    _PrivacyService_ObfuscateQuery_Handler,
		},
		{
			MethodName: "ObfuscateQueryBatch",
			Handler:    _PrivacyService_ObfuscateQueryBatch_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _PrivacyService_Health_Handler,
		},
		{
			MethodName: "RecommendParams",
			Handler:    _PrivacyService_RecommendParams_Handler,
		},
		{
			MethodName: "PerturbBinaryBatch",
			Handler:    _PrivacyService_PerturbBinaryBatch_Handler,
		},
		{
			MethodName: "PerturbCategoricalBatch",
			Handler:    _PrivacyService_PerturbCategoricalBatch_Handler,
		},
		{
			MethodName: "EstimateBinaryFrequency",
			Handler:    _PrivacyService_EstimateBinaryFrequency_Handler,
		},
		{
			MethodName: "EstimateCategoricalHistogram",
			Handler:    _PrivacyService_EstimateCategoricalHistogram_Handler,
		},
		{
			MethodName: "DPAggregate",
			Handler:    _PrivacyService_DPAggregate_Handler,
		},
		{
			MethodName: "DPVectorSum",
			Handler:    _PrivacyService_DPVectorSum_Handler,
		},
		{
			MethodName: "DPAdaptiveClip",
			Handler:    _PrivacyService_DPAdaptiveClip_Handler,
		},
		{
			MethodName: "DPGroupBy",
			Handler:    _PrivacyService_DPGroupBy_Handler,
		},
		{
			MethodName: "DPVectorMean",
			Handler:    _PrivacyService_DPVectorMean_Handler,
		},
		{
			MethodName: "DynClassify",
			Handler:    _PrivacyService_DynClassify_Handler,
		},
		{
			MethodName: "DynEval",
			Handler:    _PrivacyService_DynEval_Handler,
		},
		{
			MethodName: "DynEvalRecord",
			Handler:    _PrivacyService_DynEvalRecord_Handler,
		},
		{
			MethodName: "DynStandards",
			Handler:    _PrivacyService_DynStandards_Handler,
		},
		{
			MethodName: "DynDomains",
			Handler:    _PrivacyService_DynDomains_Handler,
		},
		{
			MethodName: "DynOperators",
			Handler:    _PrivacyService_DynOperators_Handler,
		},
		{
			MethodName: "DynValidate",
			Handler:    _PrivacyService_DynValidate_Handler,
		},
		{
			MethodName: "DynGenerateProfile",
			Handler:    _PrivacyService_DynGenerateProfile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "privacy.proto",
}
