// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: services/datasource-mgr/proto/datasourcemgr.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DataSourceManagerService_Health_FullMethodName            = "/datasourcemgr.DataSourceManagerService/Health"
	DataSourceManagerService_ListDataSources_FullMethodName   = "/datasourcemgr.DataSourceManagerService/ListDataSources"
	DataSourceManagerService_GetDataSource_FullMethodName     = "/datasourcemgr.DataSourceManagerService/GetDataSource"
	DataSourceManagerService_TestConnection_FullMethodName    = "/datasourcemgr.DataSourceManagerService/TestConnection"
	DataSourceManagerService_GetRecordByIDCard_FullMethodName = "/datasourcemgr.DataSourceManagerService/GetRecordByIDCard"
)

// DataSourceManagerServiceClient is the client API for DataSourceManagerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DataSourceManagerService 模拟数据源服务 (Mock Data Source Service)
// 专为开发与调试提供模拟数据源通信与采样，生产环境将由真实数据源替代。
type DataSourceManagerServiceClient interface {
	// Health 健康检查
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	// Canonical RPC: 列出已注册数据源目录
	ListDataSources(ctx context.Context, in *ListMockSourcesRequest, opts ...grpc.CallOption) (*ListMockSourcesResponse, error)
	// 获取单个模拟数据源基本信息
	GetDataSource(ctx context.Context, in *GetDataSourceRequest, opts ...grpc.CallOption) (*DataSourceProto, error)
	// 模拟数据源连通性测试
	TestConnection(ctx context.Context, in *TestConnectionRequest, opts ...grpc.CallOption) (*TestConnectionResponse, error)
	// 按身份证号查询单条记录
	GetRecordByIDCard(ctx context.Context, in *GetRecordByIDCardRequest, opts ...grpc.CallOption) (*SingleRecordResponse, error)
}

type dataSourceManagerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDataSourceManagerServiceClient(cc grpc.ClientConnInterface) DataSourceManagerServiceClient {
	return &dataSourceManagerServiceClient{cc}
}

func (c *dataSourceManagerServiceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, DataSourceManagerService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataSourceManagerServiceClient) ListDataSources(ctx context.Context, in *ListMockSourcesRequest, opts ...grpc.CallOption) (*ListMockSourcesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMockSourcesResponse)
	err := c.cc.Invoke(ctx, DataSourceManagerService_ListDataSources_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataSourceManagerServiceClient) GetDataSource(ctx context.Context, in *GetDataSourceRequest, opts ...grpc.CallOption) (*DataSourceProto, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DataSourceProto)
	err := c.cc.Invoke(ctx, DataSourceManagerService_GetDataSource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataSourceManagerServiceClient) TestConnection(ctx context.Context, in *TestConnectionRequest, opts ...grpc.CallOption) (*TestConnectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TestConnectionResponse)
	err := c.cc.Invoke(ctx, DataSourceManagerService_TestConnection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataSourceManagerServiceClient) GetRecordByIDCard(ctx context.Context, in *GetRecordByIDCardRequest, opts ...grpc.CallOption) (*SingleRecordResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SingleRecordResponse)
	err := c.cc.Invoke(ctx, DataSourceManagerService_GetRecordByIDCard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataSourceManagerServiceServer is the server API for DataSourceManagerService service.
// All implementations must embed UnimplementedDataSourceManagerServiceServer
// for forward compatibility.
//
// DataSourceManagerService 模拟数据源服务 (Mock Data Source Service)
// 专为开发与调试提供模拟数据源通信与采样，生产环境将由真实数据源替代。
type DataSourceManagerServiceServer interface {
	// Health 健康检查
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	// Canonical RPC: 列出已注册数据源目录
	ListDataSources(context.Context, *ListMockSourcesRequest) (*ListMockSourcesResponse, error)
	// 获取单个模拟数据源基本信息
	GetDataSource(context.Context, *GetDataSourceRequest) (*DataSourceProto, error)
	// 模拟数据源连通性测试
	TestConnection(context.Context, *TestConnectionRequest) (*TestConnectionResponse, error)
	// 按身份证号查询单条记录
	GetRecordByIDCard(context.Context, *GetRecordByIDCardRequest) (*SingleRecordResponse, error)
	mustEmbedUnimplementedDataSourceManagerServiceServer()
}

// UnimplementedDataSourceManagerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDataSourceManagerServiceServer struct{}

func (UnimplementedDataSourceManagerServiceServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedDataSourceManagerServiceServer) ListDataSources(context.Context, *ListMockSourcesRequest) (*ListMockSourcesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDataSources not implemented")
}
func (UnimplementedDataSourceManagerServiceServer) GetDataSource(context.Context, *GetDataSourceRequest) (*DataSourceProto, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDataSource not implemented")
}
func (UnimplementedDataSourceManagerServiceServer) TestConnection(context.Context, *TestConnectionRequest) (*TestConnectionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TestConnection not implemented")
}
func (UnimplementedDataSourceManagerServiceServer) GetRecordByIDCard(context.Context, *GetRecordByIDCardRequest) (*SingleRecordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRecordByIDCard not implemented")
}
func (UnimplementedDataSourceManagerServiceServer) mustEmbedUnimplementedDataSourceManagerServiceServer() {
}
func (UnimplementedDataSourceManagerServiceServer) testEmbeddedByValue() {}

// UnsafeDataSourceManagerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DataSourceManagerServiceServer will
// result in compilation errors.
type UnsafeDataSourceManagerServiceServer interface {
	mustEmbedUnimplementedDataSourceManagerServiceServer()
}

func RegisterDataSourceManagerServiceServer(s grpc.ServiceRegistrar, srv DataSourceManagerServiceServer) {
	// If the following call pancis, it indicates UnimplementedDataSourceManagerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DataSourceManagerService_ServiceDesc, srv)
}

func _DataSourceManagerService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataSourceManagerServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataSourceManagerService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataSourceManagerServiceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataSourceManagerService_ListDataSources_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMockSourcesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataSourceManagerServiceServer).ListDataSources(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataSourceManagerService_ListDataSources_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataSourceManagerServiceServer).ListDataSources(ctx, req.(*ListMockSourcesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataSourceManagerService_GetDataSource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDataSourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataSourceManagerServiceServer).GetDataSource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataSourceManagerService_GetDataSource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataSourceManagerServiceServer).GetDataSource(ctx, req.(*GetDataSourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataSourceManagerService_TestConnection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestConnectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataSourceManagerServiceServer).TestConnection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataSourceManagerService_TestConnection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataSourceManagerServiceServer).TestConnection(ctx, req.(*TestConnectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataSourceManagerService_GetRecordByIDCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRecordByIDCardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataSourceManagerServiceServer).GetRecordByIDCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataSourceManagerService_GetRecordByIDCard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataSourceManagerServiceServer).GetRecordByIDCard(ctx, req.(*GetRecordByIDCardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DataSourceManagerService_ServiceDesc is the grpc.ServiceDesc for DataSourceManagerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DataSourceManagerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "datasourcemgr.DataSourceManagerService",
	HandlerType: (*DataSourceManagerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Health",
			Handler:    _DataSourceManagerService_Health_Handler,
		},
		{
			MethodName: "ListDataSources",
			Handler:    _DataSourceManagerService_ListDataSources_Handler,
		},
		{
			MethodName: "GetDataSource",
			Handler:    _DataSourceManagerService_GetDataSource_Handler,
		},
		{
			MethodName: "TestConnection",
			Handler:    _DataSourceManagerService_TestConnection_Handler,
		},
		{
			MethodName: "GetRecordByIDCard",
			Handler:    _DataSourceManagerService_GetRecordByIDCard_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/datasource-mgr/proto/datasourcemgr.proto",
}
