apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datasource-mgr-data
  labels:
    app.kubernetes.io/name: datasource-mgr
    app.kubernetes.io/component: datasource
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
