apiVersion: v1
kind: Service
metadata:
  name: datasource-mgr
  labels:
    app.kubernetes.io/name: datasource-mgr
    app.kubernetes.io/component: datasource
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: datasource-mgr
  ports:
    - name: http
      port: 8083
      targetPort: http
      protocol: TCP
      appProtocol: kubernetes.io/http
    - name: grpc
      port: 50053
      targetPort: grpc
      protocol: TCP
      appProtocol: kubernetes.io/h2c
