// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: proto/servicehub.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ServiceHubService_Health_FullMethodName              = "/servicehub.ServiceHubService/Health"
	ServiceHubService_HubStatus_FullMethodName           = "/servicehub.ServiceHubService/HubStatus"
	ServiceHubService_Dispatch_FullMethodName            = "/servicehub.ServiceHubService/Dispatch"
	ServiceHubService_ClassifyAndDispatch_FullMethodName = "/servicehub.ServiceHubService/ClassifyAndDispatch"
	ServiceHubService_GetTask_FullMethodName             = "/servicehub.ServiceHubService/GetTask"
	ServiceHubService_ListTasks_FullMethodName           = "/servicehub.ServiceHubService/ListTasks"
	ServiceHubService_PipelineStatus_FullMethodName      = "/servicehub.ServiceHubService/PipelineStatus"
	ServiceHubService_FetchAndDesensitize_FullMethodName = "/servicehub.ServiceHubService/FetchAndDesensitize"
)

// ServiceHubServiceClient is the client API for ServiceHubService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ServiceHubService 数据服务调度中枢 gRPC 服务
// ServiceHubService is the gRPC service interface for the data scheduling hub.
type ServiceHubServiceClient interface {
	// Health 健康检查（自检 + 上游 Agent 连通性）
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	// HubStatus 调度中枢状态概览
	HubStatus(ctx context.Context, in *HubStatusRequest, opts ...grpc.CallOption) (*HubStatusResponse, error)
	// Dispatch 分发脱敏/分类任务到流水线
	Dispatch(ctx context.Context, in *DispatchRequest, opts ...grpc.CallOption) (*DispatchResponse, error)
	// ClassifyAndDispatch 先分类分级，再根据敏感度自动分发脱敏策略
	ClassifyAndDispatch(ctx context.Context, in *ClassifyAndDispatchRequest, opts ...grpc.CallOption) (*ClassifyAndDispatchResponse, error)
	// GetTask 查询单个任务状态
	GetTask(ctx context.Context, in *GetTaskRequest, opts ...grpc.CallOption) (*TaskProto, error)
	// ListTasks 列出全部任务（可选按状态过滤）
	ListTasks(ctx context.Context, in *ListTasksRequest, opts ...grpc.CallOption) (*ListTasksResponse, error)
	// PipelineStatus 流水线各阶段状态
	PipelineStatus(ctx context.Context, in *PipelineStatusRequest, opts ...grpc.CallOption) (*PipelineStatusResponse, error)
	// FetchAndDesensitize 按身份证号同步拉取数据并执行分类分级+脱敏（端到端）
	FetchAndDesensitize(ctx context.Context, in *FetchAndDesensitizeRequest, opts ...grpc.CallOption) (*FetchAndDesensitizeResponse, error)
}

type serviceHubServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewServiceHubServiceClient(cc grpc.ClientConnInterface) ServiceHubServiceClient {
	return &serviceHubServiceClient{cc}
}

func (c *serviceHubServiceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, ServiceHubService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceHubServiceClient) HubStatus(ctx context.Context, in *HubStatusRequest, opts ...grpc.CallOption) (*HubStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HubStatusResponse)
	err := c.cc.Invoke(ctx, ServiceHubService_HubStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceHubServiceClient) Dispatch(ctx context.Context, in *DispatchRequest, opts ...grpc.CallOption) (*DispatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DispatchResponse)
	err := c.cc.Invoke(ctx, ServiceHubService_Dispatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceHubServiceClient) ClassifyAndDispatch(ctx context.Context, in *ClassifyAndDispatchRequest, opts ...grpc.CallOption) (*ClassifyAndDispatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClassifyAndDispatchResponse)
	err := c.cc.Invoke(ctx, ServiceHubService_ClassifyAndDispatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceHubServiceClient) GetTask(ctx context.Context, in *GetTaskRequest, opts ...grpc.CallOption) (*TaskProto, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskProto)
	err := c.cc.Invoke(ctx, ServiceHubService_GetTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceHubServiceClient) ListTasks(ctx context.Context, in *ListTasksRequest, opts ...grpc.CallOption) (*ListTasksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTasksResponse)
	err := c.cc.Invoke(ctx, ServiceHubService_ListTasks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceHubServiceClient) PipelineStatus(ctx context.Context, in *PipelineStatusRequest, opts ...grpc.CallOption) (*PipelineStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PipelineStatusResponse)
	err := c.cc.Invoke(ctx, ServiceHubService_PipelineStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceHubServiceClient) FetchAndDesensitize(ctx context.Context, in *FetchAndDesensitizeRequest, opts ...grpc.CallOption) (*FetchAndDesensitizeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FetchAndDesensitizeResponse)
	err := c.cc.Invoke(ctx, ServiceHubService_FetchAndDesensitize_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiceHubServiceServer is the server API for ServiceHubService service.
// All implementations must embed UnimplementedServiceHubServiceServer
// for forward compatibility.
//
// ServiceHubService 数据服务调度中枢 gRPC 服务
// ServiceHubService is the gRPC service interface for the data scheduling hub.
type ServiceHubServiceServer interface {
	// Health 健康检查（自检 + 上游 Agent 连通性）
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	// HubStatus 调度中枢状态概览
	HubStatus(context.Context, *HubStatusRequest) (*HubStatusResponse, error)
	// Dispatch 分发脱敏/分类任务到流水线
	Dispatch(context.Context, *DispatchRequest) (*DispatchResponse, error)
	// ClassifyAndDispatch 先分类分级，再根据敏感度自动分发脱敏策略
	ClassifyAndDispatch(context.Context, *ClassifyAndDispatchRequest) (*ClassifyAndDispatchResponse, error)
	// GetTask 查询单个任务状态
	GetTask(context.Context, *GetTaskRequest) (*TaskProto, error)
	// ListTasks 列出全部任务（可选按状态过滤）
	ListTasks(context.Context, *ListTasksRequest) (*ListTasksResponse, error)
	// PipelineStatus 流水线各阶段状态
	PipelineStatus(context.Context, *PipelineStatusRequest) (*PipelineStatusResponse, error)
	// FetchAndDesensitize 按身份证号同步拉取数据并执行分类分级+脱敏（端到端）
	FetchAndDesensitize(context.Context, *FetchAndDesensitizeRequest) (*FetchAndDesensitizeResponse, error)
	mustEmbedUnimplementedServiceHubServiceServer()
}

// UnimplementedServiceHubServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedServiceHubServiceServer struct{}

func (UnimplementedServiceHubServiceServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedServiceHubServiceServer) HubStatus(context.Context, *HubStatusRequest) (*HubStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HubStatus not implemented")
}
func (UnimplementedServiceHubServiceServer) Dispatch(context.Context, *DispatchRequest) (*DispatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Dispatch not implemented")
}
func (UnimplementedServiceHubServiceServer) ClassifyAndDispatch(context.Context, *ClassifyAndDispatchRequest) (*ClassifyAndDispatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClassifyAndDispatch not implemented")
}
func (UnimplementedServiceHubServiceServer) GetTask(context.Context, *GetTaskRequest) (*TaskProto, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTask not implemented")
}
func (UnimplementedServiceHubServiceServer) ListTasks(context.Context, *ListTasksRequest) (*ListTasksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTasks not implemented")
}
func (UnimplementedServiceHubServiceServer) PipelineStatus(context.Context, *PipelineStatusRequest) (*PipelineStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PipelineStatus not implemented")
}
func (UnimplementedServiceHubServiceServer) FetchAndDesensitize(context.Context, *FetchAndDesensitizeRequest) (*FetchAndDesensitizeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchAndDesensitize not implemented")
}
func (UnimplementedServiceHubServiceServer) mustEmbedUnimplementedServiceHubServiceServer() {}
func (UnimplementedServiceHubServiceServer) testEmbeddedByValue()                           {}

// UnsafeServiceHubServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServiceHubServiceServer will
// result in compilation errors.
type UnsafeServiceHubServiceServer interface {
	mustEmbedUnimplementedServiceHubServiceServer()
}

func RegisterServiceHubServiceServer(s grpc.ServiceRegistrar, srv ServiceHubServiceServer) {
	// If the following call pancis, it indicates UnimplementedServiceHubServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ServiceHubService_ServiceDesc, srv)
}

func _ServiceHubService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceHubServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServiceHubService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceHubServiceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceHubService_HubStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HubStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceHubServiceServer).HubStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServiceHubService_HubStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceHubServiceServer).HubStatus(ctx, req.(*HubStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceHubService_Dispatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DispatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceHubServiceServer).Dispatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServiceHubService_Dispatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceHubServiceServer).Dispatch(ctx, req.(*DispatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceHubService_ClassifyAndDispatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClassifyAndDispatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceHubServiceServer).ClassifyAndDispatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServiceHubService_ClassifyAndDispatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceHubServiceServer).ClassifyAndDispatch(ctx, req.(*ClassifyAndDispatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceHubService_GetTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceHubServiceServer).GetTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServiceHubService_GetTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceHubServiceServer).GetTask(ctx, req.(*GetTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceHubService_ListTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTasksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceHubServiceServer).ListTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServiceHubService_ListTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceHubServiceServer).ListTasks(ctx, req.(*ListTasksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceHubService_PipelineStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PipelineStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceHubServiceServer).PipelineStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServiceHubService_PipelineStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceHubServiceServer).PipelineStatus(ctx, req.(*PipelineStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceHubService_FetchAndDesensitize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchAndDesensitizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceHubServiceServer).FetchAndDesensitize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServiceHubService_FetchAndDesensitize_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceHubServiceServer).FetchAndDesensitize(ctx, req.(*FetchAndDesensitizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ServiceHubService_ServiceDesc is the grpc.ServiceDesc for ServiceHubService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ServiceHubService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "servicehub.ServiceHubService",
	HandlerType: (*ServiceHubServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Health",
			Handler:    _ServiceHubService_Health_Handler,
		},
		{
			MethodName: "HubStatus",
			Handler:    _ServiceHubService_HubStatus_Handler,
		},
		{
			MethodName: "Dispatch",
			Handler:    _ServiceHubService_Dispatch_Handler,
		},
		{
			MethodName: "ClassifyAndDispatch",
			Handler:    _ServiceHubService_ClassifyAndDispatch_Handler,
		},
		{
			MethodName: "GetTask",
			Handler:    _ServiceHubService_GetTask_Handler,
		},
		{
			MethodName: "ListTasks",
			Handler:    _ServiceHubService_ListTasks_Handler,
		},
		{
			MethodName: "PipelineStatus",
			Handler:    _ServiceHubService_PipelineStatus_Handler,
		},
		{
			MethodName: "FetchAndDesensitize",
			Handler:    _ServiceHubService_FetchAndDesensitize_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/servicehub.proto",
}
