// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: proto/auditlog.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AuditLogService_Health_FullMethodName          = "/auditlog.AuditLogService/Health"
	AuditLogService_RecordAudit_FullMethodName     = "/auditlog.AuditLogService/RecordAudit"
	AuditLogService_GetAuditLog_FullMethodName     = "/auditlog.AuditLogService/GetAuditLog"
	AuditLogService_ListAuditLogs_FullMethodName   = "/auditlog.AuditLogService/ListAuditLogs"
	AuditLogService_GetAuditStats_FullMethodName   = "/auditlog.AuditLogService/GetAuditStats"
	AuditLogService_ListSnapshots_FullMethodName   = "/auditlog.AuditLogService/ListSnapshots"
	AuditLogService_VerifyIntegrity_FullMethodName = "/auditlog.AuditLogService/VerifyIntegrity"
	AuditLogService_VerifyChain_FullMethodName     = "/auditlog.AuditLogService/VerifyChain"
	AuditLogService_GenerateReport_FullMethodName  = "/auditlog.AuditLogService/GenerateReport"
)

// AuditLogServiceClient is the client API for AuditLogService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AuditLogService 审计日志与不可篡改存证 gRPC 服务
// AuditLogService is the gRPC service interface for audit logging and tamper-proof evidence verification.
type AuditLogServiceClient interface {
	// Health 健康检查（自检 + 上游 Agent 连通性）
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	// RecordAudit 写入单条审计存证日志（支持联动生成快照与防篡改哈希链）
	RecordAudit(ctx context.Context, in *RecordAuditRequest, opts ...grpc.CallOption) (*RecordAuditResponse, error)
	// GetAuditLog 查询单条审计日志
	GetAuditLog(ctx context.Context, in *GetAuditLogRequest, opts ...grpc.CallOption) (*AuditLogProto, error)
	// ListAuditLogs 分页与多维度条件检索审计日志
	ListAuditLogs(ctx context.Context, in *ListAuditLogsRequest, opts ...grpc.CallOption) (*ListAuditLogsResponse, error)
	// GetAuditStats 获取审计与脱敏统计分析指标
	GetAuditStats(ctx context.Context, in *GetAuditStatsRequest, opts ...grpc.CallOption) (*AuditStatsResponse, error)
	// ListSnapshots 查询脱敏快照数据存证
	ListSnapshots(ctx context.Context, in *ListSnapshotsRequest, opts ...grpc.CallOption) (*ListSnapshotsResponse, error)
	// VerifyIntegrity 校验审计快照的 SHA-256 完整性与防篡改存证
	VerifyIntegrity(ctx context.Context, in *VerifyIntegrityRequest, opts ...grpc.CallOption) (*VerifyIntegrityResponse, error)
	// VerifyChain 校验全局或指定范围内的防篡改哈希链（Hash Chain）连续性
	VerifyChain(ctx context.Context, in *VerifyChainRequest, opts ...grpc.CallOption) (*VerifyChainResponse, error)
	// GenerateReport 生成合规审计与治理效能报告
	GenerateReport(ctx context.Context, in *GenerateReportRequest, opts ...grpc.CallOption) (*ComplianceReportResponse, error)
}

type auditLogServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuditLogServiceClient(cc grpc.ClientConnInterface) AuditLogServiceClient {
	return &auditLogServiceClient{cc}
}

func (c *auditLogServiceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, AuditLogService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auditLogServiceClient) RecordAudit(ctx context.Context, in *RecordAuditRequest, opts ...grpc.CallOption) (*RecordAuditResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecordAuditResponse)
	err := c.cc.Invoke(ctx, AuditLogService_RecordAudit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auditLogServiceClient) GetAuditLog(ctx context.Context, in *GetAuditLogRequest, opts ...grpc.CallOption) (*AuditLogProto, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuditLogProto)
	err := c.cc.Invoke(ctx, AuditLogService_GetAuditLog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auditLogServiceClient) ListAuditLogs(ctx context.Context, in *ListAuditLogsRequest, opts ...grpc.CallOption) (*ListAuditLogsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAuditLogsResponse)
	err := c.cc.Invoke(ctx, AuditLogService_ListAuditLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auditLogServiceClient) GetAuditStats(ctx context.Context, in *GetAuditStatsRequest, opts ...grpc.CallOption) (*AuditStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuditStatsResponse)
	err := c.cc.Invoke(ctx, AuditLogService_GetAuditStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auditLogServiceClient) ListSnapshots(ctx context.Context, in *ListSnapshotsRequest, opts ...grpc.CallOption) (*ListSnapshotsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSnapshotsResponse)
	err := c.cc.Invoke(ctx, AuditLogService_ListSnapshots_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auditLogServiceClient) VerifyIntegrity(ctx context.Context, in *VerifyIntegrityRequest, opts ...grpc.CallOption) (*VerifyIntegrityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyIntegrityResponse)
	err := c.cc.Invoke(ctx, AuditLogService_VerifyIntegrity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auditLogServiceClient) VerifyChain(ctx context.Context, in *VerifyChainRequest, opts ...grpc.CallOption) (*VerifyChainResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyChainResponse)
	err := c.cc.Invoke(ctx, AuditLogService_VerifyChain_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auditLogServiceClient) GenerateReport(ctx context.Context, in *GenerateReportRequest, opts ...grpc.CallOption) (*ComplianceReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ComplianceReportResponse)
	err := c.cc.Invoke(ctx, AuditLogService_GenerateReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuditLogServiceServer is the server API for AuditLogService service.
// All implementations must embed UnimplementedAuditLogServiceServer
// for forward compatibility.
//
// AuditLogService 审计日志与不可篡改存证 gRPC 服务
// AuditLogService is the gRPC service interface for audit logging and tamper-proof evidence verification.
type AuditLogServiceServer interface {
	// Health 健康检查（自检 + 上游 Agent 连通性）
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	// RecordAudit 写入单条审计存证日志（支持联动生成快照与防篡改哈希链）
	RecordAudit(context.Context, *RecordAuditRequest) (*RecordAuditResponse, error)
	// GetAuditLog 查询单条审计日志
	GetAuditLog(context.Context, *GetAuditLogRequest) (*AuditLogProto, error)
	// ListAuditLogs 分页与多维度条件检索审计日志
	ListAuditLogs(context.Context, *ListAuditLogsRequest) (*ListAuditLogsResponse, error)
	// GetAuditStats 获取审计与脱敏统计分析指标
	GetAuditStats(context.Context, *GetAuditStatsRequest) (*AuditStatsResponse, error)
	// ListSnapshots 查询脱敏快照数据存证
	ListSnapshots(context.Context, *ListSnapshotsRequest) (*ListSnapshotsResponse, error)
	// VerifyIntegrity 校验审计快照的 SHA-256 完整性与防篡改存证
	VerifyIntegrity(context.Context, *VerifyIntegrityRequest) (*VerifyIntegrityResponse, error)
	// VerifyChain 校验全局或指定范围内的防篡改哈希链（Hash Chain）连续性
	VerifyChain(context.Context, *VerifyChainRequest) (*VerifyChainResponse, error)
	// GenerateReport 生成合规审计与治理效能报告
	GenerateReport(context.Context, *GenerateReportRequest) (*ComplianceReportResponse, error)
	mustEmbedUnimplementedAuditLogServiceServer()
}

// UnimplementedAuditLogServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuditLogServiceServer struct{}

func (UnimplementedAuditLogServiceServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedAuditLogServiceServer) RecordAudit(context.Context, *RecordAuditRequest) (*RecordAuditResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecordAudit not implemented")
}
func (UnimplementedAuditLogServiceServer) GetAuditLog(context.Context, *GetAuditLogRequest) (*AuditLogProto, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAuditLog not implemented")
}
func (UnimplementedAuditLogServiceServer) ListAuditLogs(context.Context, *ListAuditLogsRequest) (*ListAuditLogsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAuditLogs not implemented")
}
func (UnimplementedAuditLogServiceServer) GetAuditStats(context.Context, *GetAuditStatsRequest) (*AuditStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAuditStats not implemented")
}
func (UnimplementedAuditLogServiceServer) ListSnapshots(context.Context, *ListSnapshotsRequest) (*ListSnapshotsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSnapshots not implemented")
}
func (UnimplementedAuditLogServiceServer) VerifyIntegrity(context.Context, *VerifyIntegrityRequest) (*VerifyIntegrityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyIntegrity not implemented")
}
func (UnimplementedAuditLogServiceServer) VerifyChain(context.Context, *VerifyChainRequest) (*VerifyChainResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyChain not implemented")
}
func (UnimplementedAuditLogServiceServer) GenerateReport(context.Context, *GenerateReportRequest) (*ComplianceReportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateReport not implemented")
}
func (UnimplementedAuditLogServiceServer) mustEmbedUnimplementedAuditLogServiceServer() {}
func (UnimplementedAuditLogServiceServer) testEmbeddedByValue()                         {}

// UnsafeAuditLogServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuditLogServiceServer will
// result in compilation errors.
type UnsafeAuditLogServiceServer interface {
	mustEmbedUnimplementedAuditLogServiceServer()
}

func RegisterAuditLogServiceServer(s grpc.ServiceRegistrar, srv AuditLogServiceServer) {
	// If the following call pancis, it indicates UnimplementedAuditLogServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuditLogService_ServiceDesc, srv)
}

func _AuditLogService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuditLogServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuditLogService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuditLogServiceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuditLogService_RecordAudit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordAuditRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuditLogServiceServer).RecordAudit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuditLogService_RecordAudit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuditLogServiceServer).RecordAudit(ctx, req.(*RecordAuditRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuditLogService_GetAuditLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAuditLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuditLogServiceServer).GetAuditLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuditLogService_GetAuditLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuditLogServiceServer).GetAuditLog(ctx, req.(*GetAuditLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuditLogService_ListAuditLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAuditLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuditLogServiceServer).ListAuditLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuditLogService_ListAuditLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuditLogServiceServer).ListAuditLogs(ctx, req.(*ListAuditLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuditLogService_GetAuditStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAuditStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuditLogServiceServer).GetAuditStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuditLogService_GetAuditStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuditLogServiceServer).GetAuditStats(ctx, req.(*GetAuditStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuditLogService_ListSnapshots_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSnapshotsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuditLogServiceServer).ListSnapshots(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuditLogService_ListSnapshots_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuditLogServiceServer).ListSnapshots(ctx, req.(*ListSnapshotsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuditLogService_VerifyIntegrity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyIntegrityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuditLogServiceServer).VerifyIntegrity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuditLogService_VerifyIntegrity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuditLogServiceServer).VerifyIntegrity(ctx, req.(*VerifyIntegrityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuditLogService_VerifyChain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyChainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuditLogServiceServer).VerifyChain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuditLogService_VerifyChain_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuditLogServiceServer).VerifyChain(ctx, req.(*VerifyChainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuditLogService_GenerateReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuditLogServiceServer).GenerateReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuditLogService_GenerateReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuditLogServiceServer).GenerateReport(ctx, req.(*GenerateReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuditLogService_ServiceDesc is the grpc.ServiceDesc for AuditLogService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuditLogService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "auditlog.AuditLogService",
	HandlerType: (*AuditLogServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Health",
			Handler:    _AuditLogService_Health_Handler,
		},
		{
			MethodName: "RecordAudit",
			Handler:    _AuditLogService_RecordAudit_Handler,
		},
		{
			MethodName: "GetAuditLog",
			Handler:    _AuditLogService_GetAuditLog_Handler,
		},
		{
			MethodName: "ListAuditLogs",
			Handler:    _AuditLogService_ListAuditLogs_Handler,
		},
		{
			MethodName: "GetAuditStats",
			Handler:    _AuditLogService_GetAuditStats_Handler,
		},
		{
			MethodName: "ListSnapshots",
			Handler:    _AuditLogService_ListSnapshots_Handler,
		},
		{
			MethodName: "VerifyIntegrity",
			Handler:    _AuditLogService_VerifyIntegrity_Handler,
		},
		{
			MethodName: "VerifyChain",
			Handler:    _AuditLogService_VerifyChain_Handler,
		},
		{
			MethodName: "GenerateReport",
			Handler:    _AuditLogService_GenerateReport_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/auditlog.proto",
}
