// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: datasourcemgr.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_datasourcemgr_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_datasourcemgr_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_datasourcemgr_proto_rawDescGZIP(), []int{0}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`                         // "ok"
	LatencyMs     int64                  `protobuf:"varint,2,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"` // 耗时（毫秒）
	Via           string                 `protobuf:"bytes,3,opt,name=via,proto3" json:"via,omitempty"`                               // "datasource-mgr"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_datasourcemgr_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_datasourcemgr_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_datasourcemgr_proto_rawDescGZIP(), []int{1}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetLatencyMs() int64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *HealthResponse) GetVia() string {
	if x != nil {
		return x.Via
	}
	return ""
}

type DataQueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`   // 返回条数（默认 20）
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"` // 偏移量（默认 0）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataQueryRequest) Reset() {
	*x = DataQueryRequest{}
	mi := &file_datasourcemgr_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataQueryRequest) ProtoMessage() {}

func (x *DataQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_datasourcemgr_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataQueryRequest.ProtoReflect.Descriptor instead.
func (*DataQueryRequest) Descriptor() ([]byte, []int) {
	return file_datasourcemgr_proto_rawDescGZIP(), []int{2}
}

func (x *DataQueryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *DataQueryRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type SourceDataQueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceId      string                 `protobuf:"bytes,1,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"` // "ds_yibao" | "ds_kangyang" | "ds_mock3" | "ds_mock4"
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SourceDataQueryRequest) Reset() {
	*x = SourceDataQueryRequest{}
	mi := &file_datasourcemgr_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SourceDataQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceDataQueryRequest) ProtoMessage() {}

func (x *SourceDataQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_datasourcemgr_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceDataQueryRequest.ProtoReflect.Descriptor instead.
func (*SourceDataQueryRequest) Descriptor() ([]byte, []int) {
	return file_datasourcemgr_proto_rawDescGZIP(), []int{3}
}

func (x *SourceDataQueryRequest) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *SourceDataQueryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SourceDataQueryRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type DataRowProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fields        map[string]string      `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataRowProto) Reset() {
	*x = DataRowProto{}
	mi := &file_datasourcemgr_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataRowProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataRowProto) ProtoMessage() {}

func (x *DataRowProto) ProtoReflect() protoreflect.Message {
	mi := &file_datasourcemgr_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataRowProto.ProtoReflect.Descriptor instead.
func (*DataRowProto) Descriptor() ([]byte, []int) {
	return file_datasourcemgr_proto_rawDescGZIP(), []int{4}
}

func (x *DataRowProto) GetFields() map[string]string {
	if x != nil {
		return x.Fields
	}
	return nil
}

type DataQueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceId      string                 `protobuf:"bytes,1,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	SourceName    string                 `protobuf:"bytes,2,opt,name=source_name,json=sourceName,proto3" json:"source_name,omitempty"`
	Total         int32                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,5,opt,name=offset,proto3" json:"offset,omitempty"`
	Records       []*DataRowProto        `protobuf:"bytes,6,rep,name=records,proto3" json:"records,omitempty"`
	Via           string                 `protobuf:"bytes,7,opt,name=via,proto3" json:"via,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataQueryResponse) Reset() {
	*x = DataQueryResponse{}
	mi := &file_datasourcemgr_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataQueryResponse) ProtoMessage() {}

func (x *DataQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_datasourcemgr_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataQueryResponse.ProtoReflect.Descriptor instead.
func (*DataQueryResponse) Descriptor() ([]byte, []int) {
	return file_datasourcemgr_proto_rawDescGZIP(), []int{5}
}

func (x *DataQueryResponse) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *DataQueryResponse) GetSourceName() string {
	if x != nil {
		return x.SourceName
	}
	return ""
}

func (x *DataQueryResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *DataQueryResponse) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *DataQueryResponse) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *DataQueryResponse) GetRecords() []*DataRowProto {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *DataQueryResponse) GetVia() string {
	if x != nil {
		return x.Via
	}
	return ""
}

type DataSourceProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"` // "file" | "mock"
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"` // "connected"
	RowCount      int32                  `protobuf:"varint,6,opt,name=row_count,json=rowCount,proto3" json:"row_count,omitempty"`
	Tags          []string               `protobuf:"bytes,7,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataSourceProto) Reset() {
	*x = DataSourceProto{}
	mi := &file_datasourcemgr_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataSourceProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataSourceProto) ProtoMessage() {}

func (x *DataSourceProto) ProtoReflect() protoreflect.Message {
	mi := &file_datasourcemgr_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataSourceProto.ProtoReflect.Descriptor instead.
func (*DataSourceProto) Descriptor() ([]byte, []int) {
	return file_datasourcemgr_proto_rawDescGZIP(), []int{6}
}

func (x *DataSourceProto) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DataSourceProto) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DataSourceProto) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *DataSourceProto) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *DataSourceProto) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DataSourceProto) GetRowCount() int32 {
	if x != nil {
		return x.RowCount
	}
	return 0
}

func (x *DataSourceProto) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type ListMockSourcesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMockSourcesRequest) Reset() {
	*x = ListMockSourcesRequest{}
	mi := &file_datasourcemgr_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMockSourcesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMockSourcesRequest) ProtoMessage() {}

func (x *ListMockSourcesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_datasourcemgr_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMockSourcesRequest.ProtoReflect.Descriptor instead.
func (*ListMockSourcesRequest) Descriptor() ([]byte, []int) {
	return file_datasourcemgr_proto_rawDescGZIP(), []int{7}
}

type ListMockSourcesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Sources       []*DataSourceProto     `protobuf:"bytes,2,rep,name=sources,proto3" json:"sources,omitempty"`
	Via           string                 `protobuf:"bytes,3,opt,name=via,proto3" json:"via,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMockSourcesResponse) Reset() {
	*x = ListMockSourcesResponse{}
	mi := &file_datasourcemgr_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMockSourcesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMockSourcesResponse) ProtoMessage() {}

func (x *ListMockSourcesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_datasourcemgr_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMockSourcesResponse.ProtoReflect.Descriptor instead.
func (*ListMockSourcesResponse) Descriptor() ([]byte, []int) {
	return file_datasourcemgr_proto_rawDescGZIP(), []int{8}
}

func (x *ListMockSourcesResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListMockSourcesResponse) GetSources() []*DataSourceProto {
	if x != nil {
		return x.Sources
	}
	return nil
}

func (x *ListMockSourcesResponse) GetVia() string {
	if x != nil {
		return x.Via
	}
	return ""
}

type GetDataSourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDataSourceRequest) Reset() {
	*x = GetDataSourceRequest{}
	mi := &file_datasourcemgr_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDataSourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDataSourceRequest) ProtoMessage() {}

func (x *GetDataSourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_datasourcemgr_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDataSourceRequest.ProtoReflect.Descriptor instead.
func (*GetDataSourceRequest) Descriptor() ([]byte, []int) {
	return file_datasourcemgr_proto_rawDescGZIP(), []int{9}
}

func (x *GetDataSourceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type TestConnectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestConnectionRequest) Reset() {
	*x = TestConnectionRequest{}
	mi := &file_datasourcemgr_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestConnectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestConnectionRequest) ProtoMessage() {}

func (x *TestConnectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_datasourcemgr_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestConnectionRequest.ProtoReflect.Descriptor instead.
func (*TestConnectionRequest) Descriptor() ([]byte, []int) {
	return file_datasourcemgr_proto_rawDescGZIP(), []int{10}
}

func (x *TestConnectionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type TestConnectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DatasourceId  string                 `protobuf:"bytes,1,opt,name=datasource_id,json=datasourceId,proto3" json:"datasource_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	LatencyMs     int64                  `protobuf:"varint,3,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	Via           string                 `protobuf:"bytes,4,opt,name=via,proto3" json:"via,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestConnectionResponse) Reset() {
	*x = TestConnectionResponse{}
	mi := &file_datasourcemgr_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestConnectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestConnectionResponse) ProtoMessage() {}

func (x *TestConnectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_datasourcemgr_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestConnectionResponse.ProtoReflect.Descriptor instead.
func (*TestConnectionResponse) Descriptor() ([]byte, []int) {
	return file_datasourcemgr_proto_rawDescGZIP(), []int{11}
}

func (x *TestConnectionResponse) GetDatasourceId() string {
	if x != nil {
		return x.DatasourceId
	}
	return ""
}

func (x *TestConnectionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TestConnectionResponse) GetLatencyMs() int64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *TestConnectionResponse) GetVia() string {
	if x != nil {
		return x.Via
	}
	return ""
}

type GetRecordByIDCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceId      string                 `protobuf:"bytes,1,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`   // 数据源标识，如 "ds_yibao", "ds_kangyang"
	IdCardNo      string                 `protobuf:"bytes,2,opt,name=id_card_no,json=idCardNo,proto3" json:"id_card_no,omitempty"` // 18 位公民身份证号
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecordByIDCardRequest) Reset() {
	*x = GetRecordByIDCardRequest{}
	mi := &file_datasourcemgr_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecordByIDCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecordByIDCardRequest) ProtoMessage() {}

func (x *GetRecordByIDCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_datasourcemgr_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecordByIDCardRequest.ProtoReflect.Descriptor instead.
func (*GetRecordByIDCardRequest) Descriptor() ([]byte, []int) {
	return file_datasourcemgr_proto_rawDescGZIP(), []int{12}
}

func (x *GetRecordByIDCardRequest) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *GetRecordByIDCardRequest) GetIdCardNo() string {
	if x != nil {
		return x.IdCardNo
	}
	return ""
}

type SingleRecordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DatasourceId  string                 `protobuf:"bytes,1,opt,name=datasource_id,json=datasourceId,proto3" json:"datasource_id,omitempty"` // 规范数据源标识符
	Record        *DataRowProto          `protobuf:"bytes,2,opt,name=record,proto3" json:"record,omitempty"`                                 // 查询到的单条记录
	Found         bool                   `protobuf:"varint,3,opt,name=found,proto3" json:"found,omitempty"`                                  // 是否找到匹配记录
	Via           string                 `protobuf:"bytes,4,opt,name=via,proto3" json:"via,omitempty"`                                       // 服务节点标识
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SingleRecordResponse) Reset() {
	*x = SingleRecordResponse{}
	mi := &file_datasourcemgr_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SingleRecordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SingleRecordResponse) ProtoMessage() {}

func (x *SingleRecordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_datasourcemgr_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SingleRecordResponse.ProtoReflect.Descriptor instead.
func (*SingleRecordResponse) Descriptor() ([]byte, []int) {
	return file_datasourcemgr_proto_rawDescGZIP(), []int{13}
}

func (x *SingleRecordResponse) GetDatasourceId() string {
	if x != nil {
		return x.DatasourceId
	}
	return ""
}

func (x *SingleRecordResponse) GetRecord() *DataRowProto {
	if x != nil {
		return x.Record
	}
	return nil
}

func (x *SingleRecordResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *SingleRecordResponse) GetVia() string {
	if x != nil {
		return x.Via
	}
	return ""
}

var File_datasourcemgr_proto protoreflect.FileDescriptor

const file_datasourcemgr_proto_rawDesc = "" +
	"\n" +
	"\x13datasourcemgr.proto\x12\rdatasourcemgr\"\x0f\n" +
	"\rHealthRequest\"Y\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x02 \x01(\x03R\tlatencyMs\x12\x10\n" +
	"\x03via\x18\x03 \x01(\tR\x03via\"@\n" +
	"\x10DataQueryRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\"c\n" +
	"\x16SourceDataQueryRequest\x12\x1b\n" +
	"\tsource_id\x18\x01 \x01(\tR\bsourceId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"\x8a\x01\n" +
	"\fDataRowProto\x12?\n" +
	"\x06fields\x18\x01 \x03(\v2'.datasourcemgr.DataRowProto.FieldsEntryR\x06fields\x1a9\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xde\x01\n" +
	"\x11DataQueryResponse\x12\x1b\n" +
	"\tsource_id\x18\x01 \x01(\tR\bsourceId\x12\x1f\n" +
	"\vsource_name\x18\x02 \x01(\tR\n" +
	"sourceName\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x05R\x05total\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x05 \x01(\x05R\x06offset\x125\n" +
	"\arecords\x18\x06 \x03(\v2\x1b.datasourcemgr.DataRowProtoR\arecords\x12\x10\n" +
	"\x03via\x18\a \x01(\tR\x03via\"\xb4\x01\n" +
	"\x0fDataSourceProto\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1b\n" +
	"\trow_count\x18\x06 \x01(\x05R\browCount\x12\x12\n" +
	"\x04tags\x18\a \x03(\tR\x04tags\"\x18\n" +
	"\x16ListMockSourcesRequest\"{\n" +
	"\x17ListMockSourcesResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x128\n" +
	"\asources\x18\x02 \x03(\v2\x1e.datasourcemgr.DataSourceProtoR\asources\x12\x10\n" +
	"\x03via\x18\x03 \x01(\tR\x03via\"&\n" +
	"\x14GetDataSourceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"'\n" +
	"\x15TestConnectionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x88\x01\n" +
	"\x16TestConnectionResponse\x12#\n" +
	"\rdatasource_id\x18\x01 \x01(\tR\fdatasourceId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x03 \x01(\x03R\tlatencyMs\x12\x10\n" +
	"\x03via\x18\x04 \x01(\tR\x03via\"U\n" +
	"\x18GetRecordByIDCardRequest\x12\x1b\n" +
	"\tsource_id\x18\x01 \x01(\tR\bsourceId\x12\x1c\n" +
	"\n" +
	"id_card_no\x18\x02 \x01(\tR\bidCardNo\"\x98\x01\n" +
	"\x14SingleRecordResponse\x12#\n" +
	"\rdatasource_id\x18\x01 \x01(\tR\fdatasourceId\x123\n" +
	"\x06record\x18\x02 \x01(\v2\x1b.datasourcemgr.DataRowProtoR\x06record\x12\x14\n" +
	"\x05found\x18\x03 \x01(\bR\x05found\x12\x10\n" +
	"\x03via\x18\x04 \x01(\tR\x03via2\xd5\b\n" +
	"\x18DataSourceManagerService\x12E\n" +
	"\x06Health\x12\x1c.datasourcemgr.HealthRequest\x1a\x1d.datasourcemgr.HealthResponse\x12R\n" +
	"\aGetData\x12%.datasourcemgr.SourceDataQueryRequest\x1a .datasourcemgr.DataQueryResponse\x12`\n" +
	"\x0fListDataSources\x12%.datasourcemgr.ListMockSourcesRequest\x1a&.datasourcemgr.ListMockSourcesResponse\x12Z\n" +
	"\x0fGetDataBySource\x12%.datasourcemgr.SourceDataQueryRequest\x1a .datasourcemgr.DataQueryResponse\x12T\n" +
	"\rGetDataSource\x12#.datasourcemgr.GetDataSourceRequest\x1a\x1e.datasourcemgr.DataSourceProto\x12]\n" +
	"\x0eTestConnection\x12$.datasourcemgr.TestConnectionRequest\x1a%.datasourcemgr.TestConnectionResponse\x12a\n" +
	"\x11GetRecordByIDCard\x12'.datasourcemgr.GetRecordByIDCardRequest\x1a#.datasourcemgr.SingleRecordResponse\x12V\n" +
	"\fGetYibaoData\x12\x1f.datasourcemgr.DataQueryRequest\x1a .datasourcemgr.DataQueryResponse\"\x03\x88\x02\x01\x12Y\n" +
	"\x0fGetKangyangData\x12\x1f.datasourcemgr.DataQueryRequest\x1a .datasourcemgr.DataQueryResponse\"\x03\x88\x02\x01\x12V\n" +
	"\fGetMockData3\x12\x1f.datasourcemgr.DataQueryRequest\x1a .datasourcemgr.DataQueryResponse\"\x03\x88\x02\x01\x12V\n" +
	"\fGetMockData4\x12\x1f.datasourcemgr.DataQueryRequest\x1a .datasourcemgr.DataQueryResponse\"\x03\x88\x02\x01\x12e\n" +
	"\x0fListMockSources\x12%.datasourcemgr.ListMockSourcesRequest\x1a&.datasourcemgr.ListMockSourcesResponse\"\x03\x88\x02\x01BEZCgithub.com/fengzhizi319/PrivShield-go/services/datasource-mgr/protob\x06proto3"

var (
	file_datasourcemgr_proto_rawDescOnce sync.Once
	file_datasourcemgr_proto_rawDescData []byte
)

func file_datasourcemgr_proto_rawDescGZIP() []byte {
	file_datasourcemgr_proto_rawDescOnce.Do(func() {
		file_datasourcemgr_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_datasourcemgr_proto_rawDesc), len(file_datasourcemgr_proto_rawDesc)))
	})
	return file_datasourcemgr_proto_rawDescData
}

var file_datasourcemgr_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_datasourcemgr_proto_goTypes = []any{
	(*HealthRequest)(nil),            // 0: datasourcemgr.HealthRequest
	(*HealthResponse)(nil),           // 1: datasourcemgr.HealthResponse
	(*DataQueryRequest)(nil),         // 2: datasourcemgr.DataQueryRequest
	(*SourceDataQueryRequest)(nil),   // 3: datasourcemgr.SourceDataQueryRequest
	(*DataRowProto)(nil),             // 4: datasourcemgr.DataRowProto
	(*DataQueryResponse)(nil),        // 5: datasourcemgr.DataQueryResponse
	(*DataSourceProto)(nil),          // 6: datasourcemgr.DataSourceProto
	(*ListMockSourcesRequest)(nil),   // 7: datasourcemgr.ListMockSourcesRequest
	(*ListMockSourcesResponse)(nil),  // 8: datasourcemgr.ListMockSourcesResponse
	(*GetDataSourceRequest)(nil),     // 9: datasourcemgr.GetDataSourceRequest
	(*TestConnectionRequest)(nil),    // 10: datasourcemgr.TestConnectionRequest
	(*TestConnectionResponse)(nil),   // 11: datasourcemgr.TestConnectionResponse
	(*GetRecordByIDCardRequest)(nil), // 12: datasourcemgr.GetRecordByIDCardRequest
	(*SingleRecordResponse)(nil),     // 13: datasourcemgr.SingleRecordResponse
	nil,                              // 14: datasourcemgr.DataRowProto.FieldsEntry
}
var file_datasourcemgr_proto_depIdxs = []int32{
	14, // 0: datasourcemgr.DataRowProto.fields:type_name -> datasourcemgr.DataRowProto.FieldsEntry
	4,  // 1: datasourcemgr.DataQueryResponse.records:type_name -> datasourcemgr.DataRowProto
	6,  // 2: datasourcemgr.ListMockSourcesResponse.sources:type_name -> datasourcemgr.DataSourceProto
	4,  // 3: datasourcemgr.SingleRecordResponse.record:type_name -> datasourcemgr.DataRowProto
	0,  // 4: datasourcemgr.DataSourceManagerService.Health:input_type -> datasourcemgr.HealthRequest
	3,  // 5: datasourcemgr.DataSourceManagerService.GetData:input_type -> datasourcemgr.SourceDataQueryRequest
	7,  // 6: datasourcemgr.DataSourceManagerService.ListDataSources:input_type -> datasourcemgr.ListMockSourcesRequest
	3,  // 7: datasourcemgr.DataSourceManagerService.GetDataBySource:input_type -> datasourcemgr.SourceDataQueryRequest
	9,  // 8: datasourcemgr.DataSourceManagerService.GetDataSource:input_type -> datasourcemgr.GetDataSourceRequest
	10, // 9: datasourcemgr.DataSourceManagerService.TestConnection:input_type -> datasourcemgr.TestConnectionRequest
	12, // 10: datasourcemgr.DataSourceManagerService.GetRecordByIDCard:input_type -> datasourcemgr.GetRecordByIDCardRequest
	2,  // 11: datasourcemgr.DataSourceManagerService.GetYibaoData:input_type -> datasourcemgr.DataQueryRequest
	2,  // 12: datasourcemgr.DataSourceManagerService.GetKangyangData:input_type -> datasourcemgr.DataQueryRequest
	2,  // 13: datasourcemgr.DataSourceManagerService.GetMockData3:input_type -> datasourcemgr.DataQueryRequest
	2,  // 14: datasourcemgr.DataSourceManagerService.GetMockData4:input_type -> datasourcemgr.DataQueryRequest
	7,  // 15: datasourcemgr.DataSourceManagerService.ListMockSources:input_type -> datasourcemgr.ListMockSourcesRequest
	1,  // 16: datasourcemgr.DataSourceManagerService.Health:output_type -> datasourcemgr.HealthResponse
	5,  // 17: datasourcemgr.DataSourceManagerService.GetData:output_type -> datasourcemgr.DataQueryResponse
	8,  // 18: datasourcemgr.DataSourceManagerService.ListDataSources:output_type -> datasourcemgr.ListMockSourcesResponse
	5,  // 19: datasourcemgr.DataSourceManagerService.GetDataBySource:output_type -> datasourcemgr.DataQueryResponse
	6,  // 20: datasourcemgr.DataSourceManagerService.GetDataSource:output_type -> datasourcemgr.DataSourceProto
	11, // 21: datasourcemgr.DataSourceManagerService.TestConnection:output_type -> datasourcemgr.TestConnectionResponse
	13, // 22: datasourcemgr.DataSourceManagerService.GetRecordByIDCard:output_type -> datasourcemgr.SingleRecordResponse
	5,  // 23: datasourcemgr.DataSourceManagerService.GetYibaoData:output_type -> datasourcemgr.DataQueryResponse
	5,  // 24: datasourcemgr.DataSourceManagerService.GetKangyangData:output_type -> datasourcemgr.DataQueryResponse
	5,  // 25: datasourcemgr.DataSourceManagerService.GetMockData3:output_type -> datasourcemgr.DataQueryResponse
	5,  // 26: datasourcemgr.DataSourceManagerService.GetMockData4:output_type -> datasourcemgr.DataQueryResponse
	8,  // 27: datasourcemgr.DataSourceManagerService.ListMockSources:output_type -> datasourcemgr.ListMockSourcesResponse
	16, // [16:28] is the sub-list for method output_type
	4,  // [4:16] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_datasourcemgr_proto_init() }
func file_datasourcemgr_proto_init() {
	if File_datasourcemgr_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_datasourcemgr_proto_rawDesc), len(file_datasourcemgr_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_datasourcemgr_proto_goTypes,
		DependencyIndexes: file_datasourcemgr_proto_depIdxs,
		MessageInfos:      file_datasourcemgr_proto_msgTypes,
	}.Build()
	File_datasourcemgr_proto = out.File
	file_datasourcemgr_proto_goTypes = nil
	file_datasourcemgr_proto_depIdxs = nil
}
