// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.0
// source: datasourcemgr.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DataSourceManagerService_Health_FullMethodName            = "/datasourcemgr.DataSourceManagerService/Health"
	DataSourceManagerService_GetData_FullMethodName           = "/datasourcemgr.DataSourceManagerService/GetData"
	DataSourceManagerService_ListDataSources_FullMethodName   = "/datasourcemgr.DataSourceManagerService/ListDataSources"
	DataSourceManagerService_GetDataBySource_FullMethodName   = "/datasourcemgr.DataSourceManagerService/GetDataBySource"
	DataSourceManagerService_GetDataSource_FullMethodName     = "/datasourcemgr.DataSourceManagerService/GetDataSource"
	DataSourceManagerService_TestConnection_FullMethodName    = "/datasourcemgr.DataSourceManagerService/TestConnection"
	DataSourceManagerService_GetRecordByIDCard_FullMethodName = "/datasourcemgr.DataSourceManagerService/GetRecordByIDCard"
	DataSourceManagerService_GetYibaoData_FullMethodName      = "/datasourcemgr.DataSourceManagerService/GetYibaoData"
	DataSourceManagerService_GetKangyangData_FullMethodName   = "/datasourcemgr.DataSourceManagerService/GetKangyangData"
	DataSourceManagerService_GetMockData3_FullMethodName      = "/datasourcemgr.DataSourceManagerService/GetMockData3"
	DataSourceManagerService_GetMockData4_FullMethodName      = "/datasourcemgr.DataSourceManagerService/GetMockData4"
	DataSourceManagerService_ListMockSources_FullMethodName   = "/datasourcemgr.DataSourceManagerService/ListMockSources"
)

// DataSourceManagerServiceClient is the client API for DataSourceManagerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DataSourceManagerService 模拟数据源服务 (Mock Data Source Service)
// 专为开发与调试提供模拟数据源通信与采样，生产环境将由真实数据源替代。
type DataSourceManagerServiceClient interface {
	// Health 健康检查
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	// Canonical RPC: 通用获取数据源切片数据
	GetData(ctx context.Context, in *SourceDataQueryRequest, opts ...grpc.CallOption) (*DataQueryResponse, error)
	// Canonical RPC: 列出已注册数据源目录
	ListDataSources(ctx context.Context, in *ListMockSourcesRequest, opts ...grpc.CallOption) (*ListMockSourcesResponse, error)
	// 通用按数据源 ID 获取模拟数据 (alias of GetData)
	GetDataBySource(ctx context.Context, in *SourceDataQueryRequest, opts ...grpc.CallOption) (*DataQueryResponse, error)
	// 获取单个模拟数据源基本信息
	GetDataSource(ctx context.Context, in *GetDataSourceRequest, opts ...grpc.CallOption) (*DataSourceProto, error)
	// 模拟数据源连通性测试
	TestConnection(ctx context.Context, in *TestConnectionRequest, opts ...grpc.CallOption) (*TestConnectionResponse, error)
	// 按身份证号查询单条记录
	GetRecordByIDCard(ctx context.Context, in *GetRecordByIDCardRequest, opts ...grpc.CallOption) (*SingleRecordResponse, error)
	// Deprecated: Do not use.
	// DEPRECATED RPCs (Sunset: 2027-02-01)
	GetYibaoData(ctx context.Context, in *DataQueryRequest, opts ...grpc.CallOption) (*DataQueryResponse, error)
	// Deprecated: Do not use.
	GetKangyangData(ctx context.Context, in *DataQueryRequest, opts ...grpc.CallOption) (*DataQueryResponse, error)
	// Deprecated: Do not use.
	GetMockData3(ctx context.Context, in *DataQueryRequest, opts ...grpc.CallOption) (*DataQueryResponse, error)
	// Deprecated: Do not use.
	GetMockData4(ctx context.Context, in *DataQueryRequest, opts ...grpc.CallOption) (*DataQueryResponse, error)
	// Deprecated: Do not use.
	ListMockSources(ctx context.Context, in *ListMockSourcesRequest, opts ...grpc.CallOption) (*ListMockSourcesResponse, error)
}

type dataSourceManagerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDataSourceManagerServiceClient(cc grpc.ClientConnInterface) DataSourceManagerServiceClient {
	return &dataSourceManagerServiceClient{cc}
}

func (c *dataSourceManagerServiceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, DataSourceManagerService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataSourceManagerServiceClient) GetData(ctx context.Context, in *SourceDataQueryRequest, opts ...grpc.CallOption) (*DataQueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DataQueryResponse)
	err := c.cc.Invoke(ctx, DataSourceManagerService_GetData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataSourceManagerServiceClient) ListDataSources(ctx context.Context, in *ListMockSourcesRequest, opts ...grpc.CallOption) (*ListMockSourcesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMockSourcesResponse)
	err := c.cc.Invoke(ctx, DataSourceManagerService_ListDataSources_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataSourceManagerServiceClient) GetDataBySource(ctx context.Context, in *SourceDataQueryRequest, opts ...grpc.CallOption) (*DataQueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DataQueryResponse)
	err := c.cc.Invoke(ctx, DataSourceManagerService_GetDataBySource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataSourceManagerServiceClient) GetDataSource(ctx context.Context, in *GetDataSourceRequest, opts ...grpc.CallOption) (*DataSourceProto, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DataSourceProto)
	err := c.cc.Invoke(ctx, DataSourceManagerService_GetDataSource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataSourceManagerServiceClient) TestConnection(ctx context.Context, in *TestConnectionRequest, opts ...grpc.CallOption) (*TestConnectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TestConnectionResponse)
	err := c.cc.Invoke(ctx, DataSourceManagerService_TestConnection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataSourceManagerServiceClient) GetRecordByIDCard(ctx context.Context, in *GetRecordByIDCardRequest, opts ...grpc.CallOption) (*SingleRecordResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SingleRecordResponse)
	err := c.cc.Invoke(ctx, DataSourceManagerService_GetRecordByIDCard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Deprecated: Do not use.
func (c *dataSourceManagerServiceClient) GetYibaoData(ctx context.Context, in *DataQueryRequest, opts ...grpc.CallOption) (*DataQueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DataQueryResponse)
	err := c.cc.Invoke(ctx, DataSourceManagerService_GetYibaoData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Deprecated: Do not use.
func (c *dataSourceManagerServiceClient) GetKangyangData(ctx context.Context, in *DataQueryRequest, opts ...grpc.CallOption) (*DataQueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DataQueryResponse)
	err := c.cc.Invoke(ctx, DataSourceManagerService_GetKangyangData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Deprecated: Do not use.
func (c *dataSourceManagerServiceClient) GetMockData3(ctx context.Context, in *DataQueryRequest, opts ...grpc.CallOption) (*DataQueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DataQueryResponse)
	err := c.cc.Invoke(ctx, DataSourceManagerService_GetMockData3_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Deprecated: Do not use.
func (c *dataSourceManagerServiceClient) GetMockData4(ctx context.Context, in *DataQueryRequest, opts ...grpc.CallOption) (*DataQueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DataQueryResponse)
	err := c.cc.Invoke(ctx, DataSourceManagerService_GetMockData4_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Deprecated: Do not use.
func (c *dataSourceManagerServiceClient) ListMockSources(ctx context.Context, in *ListMockSourcesRequest, opts ...grpc.CallOption) (*ListMockSourcesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMockSourcesResponse)
	err := c.cc.Invoke(ctx, DataSourceManagerService_ListMockSources_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataSourceManagerServiceServer is the server API for DataSourceManagerService service.
// All implementations must embed UnimplementedDataSourceManagerServiceServer
// for forward compatibility.
//
// DataSourceManagerService 模拟数据源服务 (Mock Data Source Service)
// 专为开发与调试提供模拟数据源通信与采样，生产环境将由真实数据源替代。
type DataSourceManagerServiceServer interface {
	// Health 健康检查
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	// Canonical RPC: 通用获取数据源切片数据
	GetData(context.Context, *SourceDataQueryRequest) (*DataQueryResponse, error)
	// Canonical RPC: 列出已注册数据源目录
	ListDataSources(context.Context, *ListMockSourcesRequest) (*ListMockSourcesResponse, error)
	// 通用按数据源 ID 获取模拟数据 (alias of GetData)
	GetDataBySource(context.Context, *SourceDataQueryRequest) (*DataQueryResponse, error)
	// 获取单个模拟数据源基本信息
	GetDataSource(context.Context, *GetDataSourceRequest) (*DataSourceProto, error)
	// 模拟数据源连通性测试
	TestConnection(context.Context, *TestConnectionRequest) (*TestConnectionResponse, error)
	// 按身份证号查询单条记录
	GetRecordByIDCard(context.Context, *GetRecordByIDCardRequest) (*SingleRecordResponse, error)
	// Deprecated: Do not use.
	// DEPRECATED RPCs (Sunset: 2027-02-01)
	GetYibaoData(context.Context, *DataQueryRequest) (*DataQueryResponse, error)
	// Deprecated: Do not use.
	GetKangyangData(context.Context, *DataQueryRequest) (*DataQueryResponse, error)
	// Deprecated: Do not use.
	GetMockData3(context.Context, *DataQueryRequest) (*DataQueryResponse, error)
	// Deprecated: Do not use.
	GetMockData4(context.Context, *DataQueryRequest) (*DataQueryResponse, error)
	// Deprecated: Do not use.
	ListMockSources(context.Context, *ListMockSourcesRequest) (*ListMockSourcesResponse, error)
	mustEmbedUnimplementedDataSourceManagerServiceServer()
}

// UnimplementedDataSourceManagerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDataSourceManagerServiceServer struct{}

func (UnimplementedDataSourceManagerServiceServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedDataSourceManagerServiceServer) GetData(context.Context, *SourceDataQueryRequest) (*DataQueryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetData not implemented")
}
func (UnimplementedDataSourceManagerServiceServer) ListDataSources(context.Context, *ListMockSourcesRequest) (*ListMockSourcesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDataSources not implemented")
}
func (UnimplementedDataSourceManagerServiceServer) GetDataBySource(context.Context, *SourceDataQueryRequest) (*DataQueryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDataBySource not implemented")
}
func (UnimplementedDataSourceManagerServiceServer) GetDataSource(context.Context, *GetDataSourceRequest) (*DataSourceProto, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDataSource not implemented")
}
func (UnimplementedDataSourceManagerServiceServer) TestConnection(context.Context, *TestConnectionRequest) (*TestConnectionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TestConnection not implemented")
}
func (UnimplementedDataSourceManagerServiceServer) GetRecordByIDCard(context.Context, *GetRecordByIDCardRequest) (*SingleRecordResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRecordByIDCard not implemented")
}
func (UnimplementedDataSourceManagerServiceServer) GetYibaoData(context.Context, *DataQueryRequest) (*DataQueryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetYibaoData not implemented")
}
func (UnimplementedDataSourceManagerServiceServer) GetKangyangData(context.Context, *DataQueryRequest) (*DataQueryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetKangyangData not implemented")
}
func (UnimplementedDataSourceManagerServiceServer) GetMockData3(context.Context, *DataQueryRequest) (*DataQueryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMockData3 not implemented")
}
func (UnimplementedDataSourceManagerServiceServer) GetMockData4(context.Context, *DataQueryRequest) (*DataQueryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMockData4 not implemented")
}
func (UnimplementedDataSourceManagerServiceServer) ListMockSources(context.Context, *ListMockSourcesRequest) (*ListMockSourcesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMockSources not implemented")
}
func (UnimplementedDataSourceManagerServiceServer) mustEmbedUnimplementedDataSourceManagerServiceServer() {
}
func (UnimplementedDataSourceManagerServiceServer) testEmbeddedByValue() {}

// UnsafeDataSourceManagerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DataSourceManagerServiceServer will
// result in compilation errors.
type UnsafeDataSourceManagerServiceServer interface {
	mustEmbedUnimplementedDataSourceManagerServiceServer()
}

func RegisterDataSourceManagerServiceServer(s grpc.ServiceRegistrar, srv DataSourceManagerServiceServer) {
	// If the following call panics, it indicates UnimplementedDataSourceManagerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DataSourceManagerService_ServiceDesc, srv)
}

func _DataSourceManagerService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataSourceManagerServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataSourceManagerService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataSourceManagerServiceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataSourceManagerService_GetData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SourceDataQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataSourceManagerServiceServer).GetData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataSourceManagerService_GetData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataSourceManagerServiceServer).GetData(ctx, req.(*SourceDataQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataSourceManagerService_ListDataSources_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMockSourcesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataSourceManagerServiceServer).ListDataSources(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataSourceManagerService_ListDataSources_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataSourceManagerServiceServer).ListDataSources(ctx, req.(*ListMockSourcesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataSourceManagerService_GetDataBySource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SourceDataQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataSourceManagerServiceServer).GetDataBySource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataSourceManagerService_GetDataBySource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataSourceManagerServiceServer).GetDataBySource(ctx, req.(*SourceDataQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataSourceManagerService_GetDataSource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDataSourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataSourceManagerServiceServer).GetDataSource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataSourceManagerService_GetDataSource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataSourceManagerServiceServer).GetDataSource(ctx, req.(*GetDataSourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataSourceManagerService_TestConnection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestConnectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataSourceManagerServiceServer).TestConnection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataSourceManagerService_TestConnection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataSourceManagerServiceServer).TestConnection(ctx, req.(*TestConnectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataSourceManagerService_GetRecordByIDCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRecordByIDCardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataSourceManagerServiceServer).GetRecordByIDCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataSourceManagerService_GetRecordByIDCard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataSourceManagerServiceServer).GetRecordByIDCard(ctx, req.(*GetRecordByIDCardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataSourceManagerService_GetYibaoData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DataQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataSourceManagerServiceServer).GetYibaoData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataSourceManagerService_GetYibaoData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataSourceManagerServiceServer).GetYibaoData(ctx, req.(*DataQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataSourceManagerService_GetKangyangData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DataQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataSourceManagerServiceServer).GetKangyangData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataSourceManagerService_GetKangyangData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataSourceManagerServiceServer).GetKangyangData(ctx, req.(*DataQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataSourceManagerService_GetMockData3_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DataQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataSourceManagerServiceServer).GetMockData3(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataSourceManagerService_GetMockData3_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataSourceManagerServiceServer).GetMockData3(ctx, req.(*DataQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataSourceManagerService_GetMockData4_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DataQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataSourceManagerServiceServer).GetMockData4(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataSourceManagerService_GetMockData4_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataSourceManagerServiceServer).GetMockData4(ctx, req.(*DataQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataSourceManagerService_ListMockSources_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMockSourcesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataSourceManagerServiceServer).ListMockSources(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataSourceManagerService_ListMockSources_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataSourceManagerServiceServer).ListMockSources(ctx, req.(*ListMockSourcesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DataSourceManagerService_ServiceDesc is the grpc.ServiceDesc for DataSourceManagerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DataSourceManagerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "datasourcemgr.DataSourceManagerService",
	HandlerType: (*DataSourceManagerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Health",
			Handler:    _DataSourceManagerService_Health_Handler,
		},
		{
			MethodName: "GetData",
			Handler:    _DataSourceManagerService_GetData_Handler,
		},
		{
			MethodName: "ListDataSources",
			Handler:    _DataSourceManagerService_ListDataSources_Handler,
		},
		{
			MethodName: "GetDataBySource",
			Handler:    _DataSourceManagerService_GetDataBySource_Handler,
		},
		{
			MethodName: "GetDataSource",
			Handler:    _DataSourceManagerService_GetDataSource_Handler,
		},
		{
			MethodName: "TestConnection",
			Handler:    _DataSourceManagerService_TestConnection_Handler,
		},
		{
			MethodName: "GetRecordByIDCard",
			Handler:    _DataSourceManagerService_GetRecordByIDCard_Handler,
		},
		{
			MethodName: "GetYibaoData",
			Handler:    _DataSourceManagerService_GetYibaoData_Handler,
		},
		{
			MethodName: "GetKangyangData",
			Handler:    _DataSourceManagerService_GetKangyangData_Handler,
		},
		{
			MethodName: "GetMockData3",
			Handler:    _DataSourceManagerService_GetMockData3_Handler,
		},
		{
			MethodName: "GetMockData4",
			Handler:    _DataSourceManagerService_GetMockData4_Handler,
		},
		{
			MethodName: "ListMockSources",
			Handler:    _DataSourceManagerService_ListMockSources_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "datasourcemgr.proto",
}
